### ISSUE TITLE
Way to gracefully quit.

### ISSUE THREAD

**Issue by JavidPack** [j-e-k/poketrainer#100]
I can't figure out any way to quit other than ctrl-c. It would be nice to have some way of terminating without killing the process forcefully.

**Comment by j-e-k** [comment]
Especially with the new version using threading, SIGINT (Ctrl-c) is pretty much the UNIX best practice for killing a process. What else do you have in mind?

**Comment by JavidPack** [comment]
I guess just the occasional screen like this just made me worry that the program didn't like how it was being closed: http://i.imgur.com/nUQCQxe.png

I would just think in the main loop you could check if the 'q' key is pressed, but keeping it how it is is fine by me. It was just a suggestion.

**Comment by j-e-k** [comment]
Oh, I didn't realize that behavior was occurring on windows, that is a bug in and of itself and I shall take a look when I get a chance -- exiting should indeed be graceful :)

**Comment by JavidPack** [comment]
Ok. I'd say it happens maybe 1 out of 8 times.

**Comment by Zyrixion** [comment]
I've not actually experienced this issue myself at all.  What version of windows/python are you using?

**Comment by charredchar** [comment]
I have not experienced this issue on Windows either, I could check your Python install.

**Comment by JavidPack** [comment]
If no one else has ever had it happen, then I guess it's just me and this issue can be closed.

Here is a screenshot of my version and module versions: http://i.imgur.com/3SNxhEv.png

**Comment by j-e-k** [comment]
I don't have a windows VM so I can't really address this. Sorry!
