### ISSUE TITLE
Can't add some pokemon to evolution list

### ISSUE THREAD

**Issue by fil676** [j-e-k/poketrainer#104]
In the config.json file, adding CLEFAIRY, GEODUDE, and any of NIDORAN/NIDORANF/NIDORAN FEMALE etc. causes an error. I'm guessing these are identified with different names but I can't figure out what they might be.

![geodude](https://cloud.githubusercontent.com/assets/7028858/17132299/1da9862e-52ef-11e6-88c7-7a202f14b03f.PNG)

That happens if I add "GEODUDE":25, to the list.

I currently have this and it runs well:

`      "POKEMON_EVOLUTION": {
        "PIDGEY":12,
        "WEEDLE":12,
        "CATERPIE":12,
        "ZUBAT":50,
        "SPEAROW":50,
        "RATTATA":25,
        "EKANS":50,
        "PARAS":50,
        "VENONAT":50,
        "DIGLETT":50,
        "MEOWTH":50,
        "PONYTA":50,
        "DODUO":50,
        "SEEL":50,
        "SHELLDER":50,
        "VOLTORB":50,
        "KRABBY":50,
        "CUBONE":50,
        "HORSEA":50,
        "GOLDEEN":50,
        "STARYU":50,
        "MAGNEMITE":50,
        "EEVEE":25,
        "ODDISH":25,
        "POLIWAG":25,
        "BELLSPROUT":25,
        "MACHOP":25,
        "VULPIX":50,
        "JIGGLYPUFF":50,
        "SANDSHREW":50,
        "PSYDUCK":50,
        "MANKEY":50,
        "GROWLITHE":50,
        "TENTACOOL":50,
        "SLOWPOKE":50,
        "GRIMER":50,
        "DROWZEE":50,
        "RHYHORN":50 
      },`

**Comment by fil676** [comment]
Ok so instead of deleting this, I found the problem.  There are misspellings in the Enums_pb2.py file.  Clefairy is misspelled Clefary, Geodude is misspelled Geoduge.  Nidoran female is Nidoran_female and Nidoran male is Nidoran_male.  Not sure if those misspellings will be fixed in the enum, but I'll just use the misspelled versions in my evolution list for now.

The list from Enums_pb2.py:

`BULBASAUR = 1
IVYSAUR = 2
VENUSAUR = 3
CHARMENDER = 4
CHARMELEON = 5
CHARIZARD = 6
SQUIRTLE = 7
WARTORTLE = 8
BLASTOISE = 9
CATERPIE = 10
METAPOD = 11
BUTTERFREE = 12
WEEDLE = 13
KAKUNA = 14
BEEDRILL = 15
PIDGEY = 16
PIDGEOTTO = 17
PIDGEOT = 18
RATTATA = 19
RATICATE = 20
SPEAROW = 21
FEAROW = 22
EKANS = 23
ARBOK = 24
PIKACHU = 25
RAICHU = 26
SANDSHREW = 27
SANDLASH = 28
NIDORAN_FEMALE = 29
NIDORINA = 30
NIDOQUEEN = 31
NIDORAN_MALE = 32
NIDORINO = 33
NIDOKING = 34
CLEFARY = 35
CLEFABLE = 36
VULPIX = 37
NINETALES = 38
JIGGLYPUFF = 39
WIGGLYTUFF = 40
ZUBAT = 41
GOLBAT = 42
ODDISH = 43
GLOOM = 44
VILEPLUME = 45
PARAS = 46
PARASECT = 47
VENONAT = 48
VENOMOTH = 49
DIGLETT = 50
DUGTRIO = 51
MEOWTH = 52
PERSIAN = 53
PSYDUCK = 54
GOLDUCK = 55
MANKEY = 56
PRIMEAPE = 57
GROWLITHE = 58
ARCANINE = 59
POLIWAG = 60
POLIWHIRL = 61
POLIWRATH = 62
ABRA = 63
KADABRA = 64
ALAKHAZAM = 65
MACHOP = 66
MACHOKE = 67
MACHAMP = 68
BELLSPROUT = 69
WEEPINBELL = 70
VICTREEBELL = 71
TENTACOOL = 72
TENTACRUEL = 73
GEODUGE = 74
GRAVELER = 75
GOLEM = 76
PONYTA = 77
RAPIDASH = 78
SLOWPOKE = 79
SLOWBRO = 80
MAGNEMITE = 81
MAGNETON = 82
FARFETCHD = 83
DODUO = 84
DODRIO = 85
SEEL = 86
DEWGONG = 87
GRIMER = 88
MUK = 89
SHELLDER = 90
CLOYSTER = 91
GASTLY = 92
HAUNTER = 93
GENGAR = 94
ONIX = 95
DROWZEE = 96
HYPNO = 97
KRABBY = 98
KINGLER = 99
VOLTORB = 100
ELECTRODE = 101
EXEGGCUTE = 102
EXEGGUTOR = 103
CUBONE = 104
MAROWAK = 105
HITMONLEE = 106
HITMONCHAN = 107
LICKITUNG = 108
KOFFING = 109
WEEZING = 110
RHYHORN = 111
RHYDON = 112
CHANSEY = 113
TANGELA = 114
KANGASKHAN = 115
HORSEA = 116
SEADRA = 117
GOLDEEN = 118
SEAKING = 119
STARYU = 120
STARMIE = 121
MR_MIME = 122
SCYTHER = 123
JYNX = 124
ELECTABUZZ = 125
MAGMAR = 126
PINSIR = 127
TAUROS = 128
MAGIKARP = 129
GYARADOS = 130
LAPRAS = 131
DITTO = 132
EEVEE = 133
VAPOREON = 134
JOLTEON = 135
FLAREON = 136
PORYGON = 137
OMANYTE = 138
OMASTAR = 139
KABUTO = 140
KABUTOPS = 141
AERODACTYL = 142
SNORLAX = 143
ARTICUNO = 144
ZAPDOS = 145
MOLTRES = 146
DRATINI = 147
DRAGONAIR = 148
DRAGONITE = 149
MEWTWO = 150
MEW = 151`

**Comment by sharzephoue** [comment]
hey, in wich file and line you enter your first line of commands to do the evolving ??

**Comment by VK432** [comment]
You enter them in the config.JSON file, you may need to pull the latest version though.
Also Charmander is missspelled Charmender in places

**Comment by sharzephoue** [comment]
ok thanks i just saw the update

**Comment by joychugh** [comment]
Sorry about the spelling, We didn't make the enums, it came from AEONLUCID's repo. let me update uRL in readme so people can find the names

**Comment by joychugh** [comment]
It is in Readme  

For Chosing what Items to keep, get the names here, AeonLucidProtos_ItemID For Choosing what pokemon to keep get the names here,AeonLucidProtos_Pokemon
(check readme for url)

**Comment by fil676** [comment]
I'm sorry @joychugh but I still can't figure out how to set nidoran male & female to evolve.  It seems the problem stems from the fact that they're called NIDORAN_MALE and NIDORAN_FEMALE but the family names are NIDORAN and NIDORAN2.  So for example if I put in NIDORAN_MALE in the evolve list, I get an error saying that there is no family FAMILY_NIDORAN_MALE.
