### ISSUE TITLE
Wasting ultra balls on trash pokemon

### ISSUE THREAD

**Issue by bicheichane** [j-e-k/poketrainer#117]
Hey guys just trying to gather some feedback on this to see if it's just me interested in this. I have currently burned through all my pokeball stash except for ultra balls, so now even with me spinning pokestops I don't have enough pokeball income to cover for my catches, which leaves me using ultra balls to catch pidgeys and whatnot. I've been thinking about implementing an ultra ball limiter, that under certain conditions like number of ultraballs you have, if you already have the pokemon you are trying to catch, or if that pokemon is a priority for you, the bot would decide if it was worth it using an ultra ball on that catch or just running off.

What do you guys think?

**Comment by j-e-k** [comment]
A better mechanism of selecting which pokeball to use/fruits etc should be added. Pull requests for this would be much appreciated
Thanks! 😄

**Comment by bicheichane** [comment]
Well, I'm gonna start with limiting ultra ball usage for special occasions, and we'll go from there :)

**Comment by spamfarm** [comment]
Would this algorithm work?

If <pokemon encountered> CP > <current highest pokemon of this type> then:
  ignore `MAX_CATCH_ATTEMPTS`
  use raspberry
  use highest level ball available

?

**Comment by j-e-k** [comment]
We have a basic version of this implemented now. Closing.
