### ISSUE TITLE
Figure out a way to auto-use Lucky Eggs

### ISSUE THREAD

**Issue by xezero** [j-e-k/poketrainer#128]
I tried messing around with
`self.useItemXPBoost()`
`self.call()`

but it had no effect (no errors, but empty response), so not sure if the protobuf for it isn't correct/implemented or if I'm missing something else.

Nonetheless, this would be great if we could figure it out since we could stock up on tons of lucky eggs beforehand and then just have the bot double down on XP across the board.

**Comment by skydrome** [comment]
it should be `use_item_xp_boost(item_id=301)`

**Comment by xezero** [comment]
Ah that's right, forgot about underscore convention in python. Thanks @skydrome!

**Comment by xezero** [comment]
Made a pull req to do this in #131
