### ISSUE TITLE
GITHUB REPO BROKEN -- WILL BE FIXED BY THEM SHORTLY

### ISSUE THREAD

**Issue by j-e-k** [j-e-k/poketrainer#129]
Emailed github support, should be fixed shortly. Something must have gotten messed up in the rename?

**Comment by Alexey2532** [comment]
ayyy lmao, dafaq

**Comment by j-e-k** [comment]
💢

**Comment by Alexey2532** [comment]
btw, what did tomthebotter change? im using "his" bot atm, but your should be the original, any difference?

**Comment by j-e-k** [comment]
He just removed license code and was using a very old version of this code base, he also renamed a few variables randomly and deleted white space. That is it as far as I can tell....

**Comment by Jay1** [comment]
yea I worked on the other project and we basically fixed bugs that was already fixed on your version here....    we wasted a lot of time

**Comment by sontek** [comment]
@Alexey2532 Yeah, I started off using the TomTheBotter code, this codebase has more improvements and works better in my opinion.  I'd stay away from the TomTheBotter one... I also wasted time fixing things.

**Comment by Jay1** [comment]
I'm glad @j-e-k came at some point... nobody knew what was happening over there. I became suspicious because he was not accepting our PR and didn't understand what was going on

**Comment by Alexey2532** [comment]
Well, can't wait to dl it. :D Github pls fix now ^^

**Comment by Zyrixion** [comment]
I also ended up switching over when j-e-k's post landed in the git.  It's much better here anyways, as it usually is with source works.

**Comment by Alexey2532** [comment]
Now i really want to test it... xD

**Comment by loveinpin** [comment]
yeah  same here....

**Comment by Alexey2532** [comment]
Anyone can upload it to mega? if yes don't forget to remove your data in the config!

**Comment by s1gnalrunner** [comment]
RIPPERONI

**Comment by loveinpin** [comment]
I hav whole package

**Comment by sontek** [comment]
I could push up my latest master/develop branches I have locally if github can't fix it.  I was actively pulling so I believe I have everything.

**Comment by j-e-k** [comment]
I think master/develop are working now. Do they match your version? Still waiting to hear back from github support....

**Comment by j-e-k** [comment]
Meh seems like it is fixed now, awesome
