### ISSUE TITLE
Failed to catch pokemon!

### ISSUE THREAD

**Issue by moeops** [j-e-k/poketrainer#132]
Runs smoothly, everything working but suddenly it says, failed to catch pokemon every time it sees a pokemon.

I'm not softbanned, pretty sure.

Thank you for this btw.

**Comment by omlet05** [comment]
same here :-(

**Comment by Alexey2532** [comment]
did you freshly dl it?

**Comment by moeops** [comment]
Yes sir. It suddenly fixed itself? Starting to catch pokemon now.

**Comment by Alexey2532** [comment]
You tpd. There is a different location. have the same xD eZ soft ban ^^

**Comment by moeops** [comment]
@Alexey2532 Oh I see, btw do you know the correct syntax for writing down the IDs of to keep pokemon?

**Comment by moeops** [comment]
"KEEP_POKEMON_NAMES": ["GASTLY"],
      "THROW_POKEMON_NAMES": ["PIDGEY"],

So let's say I want to add Rattata to pokemon that will be thrown away, how do I do that?

**Comment by Alexey2532** [comment]
@moeops Im sorry, can't help you

**Comment by Alexey2532** [comment]
@moeops 
  "KEEP_POKEMON_NAMES": ["GASTLY"],
  "THROW_POKEMON_NAMES": ["PIDGEY"],
  "THROW_POKEMON_NAMES": ["POKEMON"],

That should work

**Comment by Zyrixion** [comment]
`      "KEEP_POKEMON_NAMES": ["MEWTWO", "MEW", "SNORLAX", "LAPRAS", "DRAGONITE", "GYARADOS", "CHANSEY", "AERODACTYL"],
      "THROW_POKEMON_NAMES": ["ZUBAT", "GOLBAT", "RATICATE"],`

**Comment by COLDPOKEMONGO** [comment]
on this, the --cached command doesn't seem to work on dev.

**Comment by j-e-k** [comment]
`cached` has been removed from development for now since it was a jank implementation
