### ISSUE TITLE
Latest Build Not Evolving Pidgey/Weedle.

### ISSUE THREAD

**Issue by freakyfreak87** [j-e-k/poketrainer#134]
the latest pull it seems after the update isnt evolving pidgeys or weedles, also caterpie needs added, but im noy 100% certain how to do that myself.

**Comment by freakyfreak87** [comment]
`{"accounts" :
    [{
        "auth_service": "google",
        "username": "XXXXXXX",
        "password": "XXXXXXX",
        "location": "XXXXXX",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": "XXXXXXX",
        "MIN_KEEP_IV" : 90,
        "KEEP_CP_OVER": 700,
        "STEP_SIZE": 75,
        "EXPERIMENTAL": true,
        "SKIP_VISITED_FORT_DURATION": 600,
        "SPIN_ALL_FORTS": true,
        "KEEP_POKEMON_IDS": [129]
    },
    {  "auth_service": "ptc",
        "username": "someusername",
        "password": "password",
        "location": "University of Southern California, Los Angeles, CA",
        "USE_GOOGLE": false,
        "MIN_KEEP_IV" : 70
    }
    ]}
`

**Comment by Jay1** [comment]
```
"POKEMON_EVOLUTION": {
        "PIDGEY": 12,
        "WEEDLE":12,
        "CATERPIE"12
      },
```
This would add caterpie

**Comment by freakyfreak87** [comment]
in the json config file it has what you posted, biut also under pokemon "throw" it has pidget could it possibly be recycling them because of that before it evolves them?

` "POKEMON_EVOLUTION": {
        "PIDGEY": 12,
        "WEEDLE":12,
        "CATERPIE"12
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": ["MEWTWO"],
      "THROW_POKEMON_NAMES": ["PIDGEY"],
 `

**Comment by joychugh** [comment]
if you had bag full, it will clean the pokemon (xfer) so that may have happened

**Comment by freakyfreak87** [comment]
neither my bag nor pokemon are full

**Comment by jordsmi** [comment]
Not sure why its not working before but I think you are missing the colon when adding caterpie..

"CATERPIE":12 instead of "CATERPIE"12

**Comment by freakyfreak87** [comment]
ugh this is annoying i have over 1500 pidgey candy and it just recycles all the caught pidgey

**Comment by freakyfreak87** [comment]
okay I get this when I try to add the caterpie line, what am I doing wrong?

`
C:\Users\Jeremy\Desktop\current\poketrainer-master>PYTHON pokecli.py -i 0
Traceback (most recent call last):
  File "pokecli.py", line 140, in <module>
    main()
  File "pokecli.py", line 102, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 30 column 21 (char 870)`

**Comment by rolanddu85** [comment]
Are you missing a comma between "WEEDLE":12 and "CATERPIE":12?

**Comment by j-e-k** [comment]
You are indeed missing a comma, that is a json error my friend. Check out http://jsonlint.com/ to make sure your config is valid

**Comment by freakyfreak87** [comment]
lol not long after i posted that I seen the comma was missing, dumb ass here lol.

**Comment by j-e-k** [comment]
No problem. Glad it is workign for you now 😄
