### ISSUE TITLE
PTC Issue

### ISSUE THREAD

**Issue by Alexey2532** [j-e-k/poketrainer#135]
{
  "accounts": [
    {
      "auth_service": "google",
      "username": "test@gmail.com",
      "password": "password",
      "location": "University of Southern California, Los Angeles, CA",
      "USE_GOOGLE": true,
      "GMAPS_API_KEY": "some api key here",
      "MIN_KEEP_IV": 50,
      "KEEP_CP_OVER": 500,
      "STEP_SIZE": 100,
      "EXPERIMENTAL": true,
      "SKIP_VISITED_FORT_DURATION": 600,
      "SPIN_ALL_FORTS": true,
      "STAY_WITHIN_PROXIMITY": 500,
      "MIN_ITEMS": {
        "ITEM_POTION": 10,
        "ITEM_SUPER_POTION": 10,
        "ITEM_HYPER_POTION": 10,
        "ITEM_MAX_POTION": 20,
        "ITEM_BLUK_BERRY": 10,
        "ITEM_NANAB_BERRY": 10,
        "ITEM_REVIVE": 10,
        "ITEM_MAX_REVIVE": 10,
        "ITEM_RAZZ_BERRY": 10
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 12,
        "WEEDLE":12 
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": ["MEWTWO"],
      "THROW_POKEMON_NAMES": ["PIDGEY"],
      "MAX_CATCH_ATTEMPTS": 10
    },

This dose not work with the ptc, it "tp's" 100m and dosent throw away.

**Comment by j-e-k** [comment]
Going to need some more details, what do you mean by `This dose not work with the ptc, it "tp's" 100m and dosent throw away.` Can you paste the full log with your username redacted? Thanks

**Comment by Alexey2532** [comment]
idk how to show it, its like normal but if you look on the web map he makes big jumps and dosent throw away and dosen't evolve.

**Comment by disintonic** [comment]
Lower this value to stop big jumps from happening (I have mine at 10):
`"STEP_SIZE": 100,`

The only way I was able to get the program to throw away duplicates that don't meet the CP and IV criteria was adding each pokemon name to this value (If you check you should only have one Pidgey in your bag):
`"THROW_POKEMON_NAMES": ["PIDGEY"],`

I don't believe this version of the API evolves Pokemon for you yet.

**Comment by Alexey2532** [comment]
yes, still not working.

**Comment by disintonic** [comment]
Copy your current config.json settings like you did above, just with the values you are using (redact the private data).

**Comment by Alexey2532** [comment]
i just use my old file, works way better.

**Comment by Alexey2532** [comment]
{
  "accounts": [
    {
      "auth_service": "google",
      "username": "test@gmail.com",
      "password": "password",
      "location": "Central Park, New York, NY",
      "USE_GOOGLE": true,
      "GMAPS_API_KEY": "my key",
      "MIN_KEEP_IV": 80,
      "KEEP_CP_OVER": 1300,
      "STEP_SIZE": 10,
      "EXPERIMENTAL": true,
      "SKIP_VISITED_FORT_DURATION": 600,
      "SPIN_ALL_FORTS": true,
      "STAY_WITHIN_PROXIMITY": 500,
      "MIN_ITEMS": {
        "ITEM_POTION": 10,
        "ITEM_SUPER_POTION": 10,
        "ITEM_HYPER_POTION": 10,
        "ITEM_MAX_POTION": 20,
        "ITEM_BLUK_BERRY": 10,
        "ITEM_NANAB_BERRY": 10,
        "ITEM_REVIVE": 10,
        "ITEM_MAX_REVIVE": 10,
        "ITEM_RAZZ_BERRY": 10
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 12,
        "WEEDLE":12 
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": ["MEWTWO"],
      "THROW_POKEMON_NAMES": ["PIDGEY"],
      "MAX_CATCH_ATTEMPTS": 10
    },
    {
      "auth_service": "ptc",
      "username": "ikk",
      "password": "s",
      "location": "Central Park, New York, NY",
      "USE_GOOGLE": false,
      "MIN_KEEP_IV": 80
    }
  ]
}

**Comment by disintonic** [comment]
You shouldn't be moving far each step if you are using the first account (indexed as 0), however that does not mean the web interface updates with each step. It looks like it updates in intervals, so even with a small step value the web map will still show large jumps. As for throwing and evolving, you currently only have it set to throw away Pidgeys and evolve Pidgeys and Weedles. Add other pokemon names to `POKEMON_EVOLUTION` and `THROW_POKEMON_NAMES` to use these features.

**Comment by Alexey2532** [comment]
i don't use this config, i use a older one, it walks the 10 steps i want to and throws perfectly away.
