### ISSUE TITLE
Refactor logging for multi account mode

### ISSUE THREAD

**Issue by j-e-k** [j-e-k/poketrainer#139]
Follow up of discussion at end of #123. Logging needs to be improved on the development branch.

**Comment by sontek** [comment]
Now that I'm using the multi-user processes more the more I'm running into issues, so I'm not sure if overall it is going to be a good idea.

For example, right now I have one account I want to change its location in the config but to do that I have to shutdown *all* the accounts.

**Comment by j-e-k** [comment]
The multi account mode really isn't ready for prime time yet, I need to move all of the command line features to web.py and then provide both a web interface and document the API to make it easy to automate....Commit forthcoming shortly on location setting

**Comment by j-e-k** [comment]
I guess a better feature would be to be able to restart an account's bot thread from the web thread.

**Comment by j-e-k** [comment]
see #142 
Will sleep on it for tonight

**Comment by j-e-k** [comment]
Will revisit this in a separate branch so as to not hold up on merging develop into master.
