### ISSUE TITLE
Evolve or Upgrade

### ISSUE THREAD

**Issue by grobins** [j-e-k/poketrainer#144]
Is there a way to upgrade pokemon that are no longer capable of evolving? I'm collecting tons of candy, but as I level up, the pokemon have a large range of available CP to upgrade.

**Comment by beeedy** [comment]
I had a system in place that would evolve all pokemon to their final evolution and then you could decide if it should level up the final evolution or if it should evolve another one to the final evolution. At the moment the code base seems too volatile however I hope to implement it once things calm down and I can merge without worry of toes getting stepped on

**Comment by grobins** [comment]
Can u send me your commit? I'll have a tinker until it gets merged into
master

**Comment by beeedy** [comment]
It was just merged into the development branch, feel free to pull that and it will be there!

**Comment by grobins** [comment]
Will do, thanks

**Comment by Zyrixion** [comment]
TBH I think this is something that should be left for people to manually do, since it doesn't really serve a purpose in terms of the automation, for levelling, catching, etc.  Most people would probably have little use for this, as they likely want more control of how their stardust/candies are spent, and it hurts nothing to leave it completely manual.

**Comment by grobins** [comment]
agrree that it's a personal choice, but collecting 500 candies and having
to manually upgrade each time is a pain.  There are enough candies
 obtained to ensure we'll not run out, as long as evolving is the priority

**Comment by beeedy** [comment]
@Zyrixion I could not disagree with you more. I completely respect your opinion, and by no means would this feature (if implemented) be forced upon users or enabled by default. Personally I am interested in the bot being able to grind its way to a full pokedex, with one of every pokemon - this is my final goal. To achieve this at a faster pace than relying upon luck to find them all the bot needs to have the ability to evolve pokemon. 

Secondly, evolving a pokemon gives you 500xp, 1000xp if using a lucky egg. If you have a bot that can crank through a few hundred evolutions in the 30min a lucky age is active.... well you can see where this is going.

**Comment by j-e-k** [comment]
I am going to close this, trying to reduce feature bloat. Will revisit in future.
