### ISSUE TITLE
Releasing Pokemon due to nicknaming

### ISSUE THREAD

**Issue by COLDPOKEMONGO** [j-e-k/poketrainer#148]
Currently when you nickname a pokemon, the pokemon that will get released if it satisfies the CP or the IV criteria. 

However, if it is the only type of pokemon, it will not be released yet.

**Comment by playboz84** [comment]
How is that an issue? Send me your config file.

**Comment by COLDPOKEMONGO** [comment]
Oh, possible config error?  I'll quote the important bits: 

"KEEP_CP_OVER": 1400,
      "KEEP_IV_OVER": 90,
      "KEEP_IV_MIN_PERCENT_CP": 0,
      "MAX_POKEMON_HIGH_IV": 999,
 
 "POKEMON_EVOLUTION": {"PIDGEY":12,"WEEDLE":12,"CATERPIE":12,"ZUBAT":25,"RATTATA":25,"DROWZEE":50,"STARYU":50,"POLIWAG":25,"GOLDEEN":50,"KRABBY":50,"SPEAROW":50,"DODUO":50},
      
"MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": 
["MEWTWO","LAPRAS","SNORLAX","BLASTOISE","CHARIZARD","VENUSAUR","AERODACTYL","GYARADOS","VAPOREON","EXEGGCUTE","CHANSEY","MEW","ALAKAZAM","GENGAR","MACHAMP","VAPOREON","FLAREON"],
      "THROW_POKEMON_NAMES": 
["PIDGEOTTO","GOLBAT","RATICATE","SEAKING","GOLDUCK","STARMIE","METAPOD","KAKUNA","KINGLER","FEAROW","DODRIO"],

**Comment by COLDPOKEMONGO** [comment]
Oh wait I think my issue is addressed in #85
