### ISSUE TITLE
Web Interface is borked

### ISSUE THREAD

**Issue by DirtyCajunRice** [j-e-k/poketrainer#149]
* Running on http://10.0.10.105:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 276-549-337
10.0.10.2 - - [27/Jul/2016 04:15:50] "GET / HTTP/1.1" 404 -
10.0.10.2 - - [27/Jul/2016 04:17:25] "GET / HTTP/1.1" 404 -
10.0.10.2 - - [27/Jul/2016 04:17:26] "GET / HTTP/1.1" 404 -
10.0.10.2 - - [27/Jul/2016 04:18:12] "GET / HTTP/1.1" 404 -

also tried 0.0.0.0 same thing.

**Comment by stef264** [comment]
There is no page in the root.
You need to go to  http://10.0.10.105:5000/<username>/pokemon

**Comment by DirtyCajunRice** [comment]
Im so dumb.

**Comment by DirtyCajunRice** [comment]
side note while i have you, Is there a mph/kph correlation to steps in config? 

also every single pokestop is saying cant spin. but i am catching pokemon

**Comment by stef264** [comment]
> Is there a mph/kph correlation to steps in config? 

I dont know exactly. The README gives a rudemantary idea.

` STEP_SIZE corresponds to how many meters you want to move at most between server calls, set this around 4-6 for walking or 100-200 for really, really fast driving`

 
> also every single pokestop is saying cant spin. but i am catching pokemon

Maybe your inventory is full? Check this first if not send me your config (don't forget to remove your private data)

**Comment by playboz84** [comment]
Tried your fix above but it wont work:
You need to go to http://10.0.10.105:5000/< username >/pokemon

What do you mean by no root?

Thanks

**Comment by stef264** [comment]
> What do you mean by no root?

There is nothing defined at http://10.0.10.105:5000/ so the webserver respond with 404

> it wont work:

You need to change the link accordingly to your webserver. (IP which web.py printed)

**Comment by DirtyCajunRice** [comment]
Is there a max value as well for items or only a min? and is there a way to prioritize certain balls? for example.... always leave atleast bag space of 10 (for new spins) and throw away pokeballs for great/ultraballs ?
