### ISSUE TITLE
Doesn't spin any forts

### ISSUE THREAD

**Issue by AtharvaVaidya** [j-e-k/poketrainer#150]
Basically I ran out of Pokeballs and now the bot isn't spinning any pokestops.

**Comment by DirtyCajunRice** [comment]
also have this issue. Mine says "could not spin pokestop"

**Comment by beeedy** [comment]
1. softban
2. servers are down/lagging

**Comment by HibikiFox** [comment]
3.  you spinned it recently and it was still on cool down, Happens if the bot resets and looses its timers. or if you config is setup with `"SKIP_VISITED_FORT_DURATION":` too short

**Comment by grobins** [comment]
Try setting "STAY_WITHIN_PROXIMITY": 0
I had the same issue and it went away after doing this.  Now I can happily spin forts.

**Comment by j-e-k** [comment]
Hopefully it works for you now!
