### ISSUE TITLE
web.py crashing

### ISSUE THREAD

**Issue by playboz84** [j-e-k/poketrainer#152]
Runs just fine but when I try to click the link to open in browser it crashes. Below is dump.

https://gist.github.com/anonymous/27921e7f70f8825a8580b929addbe671

**Comment by huntergregal** [comment]
Make sure you are NOT modifying the web.py file...specifically do not change the route in this file to add in your username. It may be tempting but the @route in this file is supposed to be USERNAME_HERE etc.

When you go to the link in your web browser, that is where you should replace  USERNAME_HERE with your username.

example:
http://localhost:5000/something@gmail.com/pokemon
or
http://localhost:5000/swagBro/pokemon

**Comment by playboz84** [comment]
That was my issue! thanks for your help 👍

**Comment by playboz84** [comment]
@huntergregal I know only one web.py can run at once but how do i see multiple accounts on the map at once? Is it even possible?

Thanks

**Comment by huntergregal** [comment]
Currently you have to open a new tab for each account:

http://localhost:5000/something@gmail.com/pokemon
http://localhost:5000/something2@gmail.com/pokemon

**Comment by huntergregal** [comment]
Under the feature bloat issue I made a suggestion to revamp the interface to support multiple accounts better and configuration. If it gets enough positive feedback ill work on implementing it.

**Comment by playboz84** [comment]
oh that would be awesome! thanks again for your help 👍

**Comment by playboz84** [comment]
@huntergregal unfortunately it wont work for my accounts because my e-mail is in this format sdfsfsdf####@gmail.com so when i put a 2 behind the ### i guess that it decipher it.

**Comment by j-e-k** [comment]
Do you mean the `#` sign or a number?

i.e. is it:
`sdfsfsdf####2@gmail.com`
`sdfsfsdf####3@gmail.com`
etc?

**Comment by playboz84** [comment]
yes its 
asdasd#####2@gmail.com
asdasda##3@gmail.com

and so on. that isnt working.

Also does it matter that each bot has their separate directory on my desktop?

**Comment by disintonic** [comment]
When web.py is ran it gets all of the data from pgoapi/data_dumps/USERNAME.json, so as long as those files exist there it should work. What is in the separate directories?

**Comment by playboz84** [comment]
i have separate folders that were made for each account that i bot. so the entire bot program is in each directory. Should it not be done like that?

**Comment by j-e-k** [comment]
web.py must be run from the same folder that data_dumps is in. There is no reason to not run every bot from the same directory due to the multiple accounts config.

**Comment by playboz84** [comment]
how would i setup a multiple accounts config file i guess is what my problem is. Would i create 3 separate config files and rename them 1, 2, and 3 or does the config file contain all 3 accounts configurations.

**Comment by disintonic** [comment]
If you are running web.py from both folders it is more than likely breaking things. To add a second profile copy everything from config.json and create a second block inside Accounts[ ]. Be sure to separate both entry blocks with a comma. It will look something like this: 

**NOTE THAT I'M USING THE DEVELOP BRANCH CONFIG NOT MASTER CONFIG**

`{
  "accounts": [
    {
      "auth_service": "ptc",
      "username": "ExampleName",
      "password": "ExamplePass",
      "location": "ExampleLoc",
      "USE_GOOGLE": true,
      "GMAPS_API_KEY": "APIKEY",
      "KEEP_CP_OVER": 800,
	  "KEEP_IV_OVER": 80,
      "KEEP_IV_MIN_PERCENT_CP": 0,
      "MAX_POKEMON_HIGH_IV": 999,
	  "AUTO_USE_LUCKY_EGG": true,
      "STEP_SIZE": 20,
      "EXPERIMENTAL": true,
      "SKIP_VISITED_FORT_DURATION": 600,
      "SPIN_ALL_FORTS": true,
      "STAY_WITHIN_PROXIMITY": 2000,
      "MIN_ITEMS": {
        "ITEM_POTION": 0,
        "ITEM_SUPER_POTION": 0,
        "ITEM_HYPER_POTION": 0,
        "ITEM_MAX_POTION": 0,
        "ITEM_BLUK_BERRY": 0,
        "ITEM_NANAB_BERRY": 0,
        "ITEM_REVIVE": 0,
        "ITEM_MAX_REVIVE": 0,
        "ITEM_RAZZ_BERRY": 0
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 12,
        "WEEDLE":12 
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": ["MEWTWO"],
      "THROW_POKEMON_NAMES": ["PIDGEY"],
      "MAX_CATCH_ATTEMPTS": 50
    },
    {
      "auth_service": "ptc",
      "username": "ExampleName2",
      "password": "ExamplePass2",
      "location": "ExampleLoc2",
      "USE_GOOGLE": true,
      "GMAPS_API_KEY": "APIKEY2",
      "KEEP_CP_OVER": 800,
	  "KEEP_IV_OVER": 80,
      "KEEP_IV_MIN_PERCENT_CP": 0,
      "MAX_POKEMON_HIGH_IV": 999,
	  "AUTO_USE_LUCKY_EGG": true,
      "STEP_SIZE": 20,
      "EXPERIMENTAL": true,
      "SKIP_VISITED_FORT_DURATION": 600,
      "SPIN_ALL_FORTS": true,
      "STAY_WITHIN_PROXIMITY": 2000,
      "MIN_ITEMS": {
        "ITEM_POTION": 0,
        "ITEM_SUPER_POTION": 0,
        "ITEM_HYPER_POTION": 0,
        "ITEM_MAX_POTION": 0,
        "ITEM_BLUK_BERRY": 0,
        "ITEM_NANAB_BERRY": 0,
        "ITEM_REVIVE": 0,
        "ITEM_MAX_REVIVE": 0,
        "ITEM_RAZZ_BERRY": 0
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 12,
        "WEEDLE":12 
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": ["MEWTWO"],
      "THROW_POKEMON_NAMES": ["PIDGEY"],
      "MAX_CATCH_ATTEMPTS": 50
    }`

**Comment by j-e-k** [comment]
It contains all configurations, check out the example config.json. "accounts" is an array of configurations. You specify which to run with `-i N` where N is the index of the account in the array

**Comment by huntergregal** [comment]
Run each account with 
```
python pokecli.py -i 0       //account 1
python pokecli.py -i 1       //account 2
python pokecli.py -i 2       //account 3
etc...
```
I redacted account logins, api keys, and location lines. but here is a multi account example:

```
{
  "accounts": [
    {
      "auth_service": "google",
      "USE_GOOGLE": true,
      "MIN_KEEP_IV": 70,
      "KEEP_CP_OVER": 1500,
      "STEP_SIZE": 150,
      "AUTO_USE_LUCKY_EGG": true,
      "EXPERIMENTAL": true,
      "SKIP_VISITED_FORT_DURATION": 600,
      "SPIN_ALL_FORTS": true,
      "STAY_WITHIN_PROXIMITY": 3500,
      "MIN_ITEMS": {
        "ITEM_POTION": 10,
        "ITEM_SUPER_POTION": 10,
        "ITEM_HYPER_POTION": 10,
        "ITEM_MAX_POTION": 20,
        "ITEM_BLUK_BERRY": 10,
        "ITEM_NANAB_BERRY": 10,
        "ITEM_REVIVE": 10,
        "ITEM_MAX_REVIVE": 10,
        "ITEM_RAZZ_BERRY": 10
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 5,
        "WEEDLE":5, 
        "RATTATA":5,
        "DODUO":5,
        "ZUBAT":5 
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": ["MEWTWO","GYARADOS","MEW","DRAGONITE","LAPRAS","KANGASKHAN","MOLTRES","ZAPDOS","ARTICUNO","DITTO"],
      "THROW_POKEMON_NAMES": ["RATICATE","GOLDEEN","DODRIO","SPEAROW","MAGIKARP"],
      "MAX_CATCH_ATTEMPTS": 10,
      "LIST_POKEMON_BEFORE_CLEANUP": false,
      "LIST_INVENTORY_BEFORE_CLEANUP": true,
      "RELEASE_DUPLICATES": true,
      "RELEASE_DUPLICATES_MAX_LV": 1500,
      "RELEASE_DUPLICATES_SCALER": 0.9,
      "DEFINE_POKEMON_LV": "CP+IV"
    },
    {
      "auth_service": "ptc",
      "USE_GOOGLE": true,
      "MIN_KEEP_IV": 95,
      "AUTO_USE_LUCKY_EGG": true,
      "KEEP_CP_OVER": 200,
      "STEP_SIZE": 150,
      "EXPERIMENTAL": true,
      "SKIP_VISITED_FORT_DURATION": 300,
      "SPIN_ALL_FORTS": true,
      "STAY_WITHIN_PROXIMITY": 3500,
      "MIN_ITEMS": {
        "ITEM_POTION": 10,
        "ITEM_SUPER_POTION": 10,
        "ITEM_HYPER_POTION": 10,
        "ITEM_MAX_POTION": 20,
        "ITEM_BLUK_BERRY": 10,
        "ITEM_NANAB_BERRY": 10,
        "ITEM_REVIVE": 10,
        "ITEM_MAX_REVIVE": 10,
        "ITEM_RAZZ_BERRY": 10
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 5,
        "WEEDLE":5, 
        "RATTATA":5,
        "DODUO":5 
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": ["MEWTWO","GYARADOS","MEW","DRAGONITE","LAPRAS","KANGASKHAN","MOLTRES","ZAPDOS","ARTICUNO","DITTO"],
      "THROW_POKEMON_NAMES": ["RATICATE","GOLDEEN","DODRIO","SPEAROW","MAGIKARP"],
      "MAX_CATCH_ATTEMPTS": 10,
      "LIST_POKEMON_BEFORE_CLEANUP": false,
      "LIST_INVENTORY_BEFORE_CLEANUP": true,
      "RELEASE_DUPLICATES": true,
      "RELEASE_DUPLICATES_MAX_LV": 1000,
      "RELEASE_DUPLICATES_SCALER": 0.9,
      "DEFINE_POKEMON_LV": "CP+IV"
    },
    {
      "auth_service": "ptc",
      "USE_GOOGLE": true,
      "MIN_KEEP_IV": 95,
      "KEEP_CP_OVER": 200,
      "AUTO_USE_LUCKY_EGG": true,
      "STEP_SIZE": 150,
      "EXPERIMENTAL": true,
      "SKIP_VISITED_FORT_DURATION": 300,
      "SPIN_ALL_FORTS": true,
      "STAY_WITHIN_PROXIMITY": 3500,
      "MIN_ITEMS": {
        "ITEM_POTION": 10,
        "ITEM_SUPER_POTION": 10,
        "ITEM_HYPER_POTION": 10,
        "ITEM_MAX_POTION": 20,
        "ITEM_BLUK_BERRY": 10,
        "ITEM_NANAB_BERRY": 10,
        "ITEM_REVIVE": 10,
        "ITEM_MAX_REVIVE": 10,
        "ITEM_RAZZ_BERRY": 10
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 5,
        "WEEDLE":5, 
        "RATTATA":5,
        "DODUO":5 
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": ["MEWTWO","GYARADOS","MEW","DRAGONITE","LAPRAS","KANGASKHAN","MOLTRES","ZAPDOS","ARTICUNO","DITTO"],
      "THROW_POKEMON_NAMES": ["RATICATE","GOLDEEN","DODRIO","SPEAROW","MAGIKARP"],
      "MAX_CATCH_ATTEMPTS": 10,
      "LIST_POKEMON_BEFORE_CLEANUP": false,
      "LIST_INVENTORY_BEFORE_CLEANUP": true,
      "RELEASE_DUPLICATES": true,
      "RELEASE_DUPLICATES_MAX_LV": 1000,
      "RELEASE_DUPLICATES_SCALER": 0.9,
      "DEFINE_POKEMON_LV": "CP+IV"
    },
    {
      "auth_service": "ptc",
      "USE_GOOGLE": true,
      "MIN_KEEP_IV": 95,
      "KEEP_CP_OVER": 200,
      "AUTO_USE_LUCKY_EGG": true,
      "STEP_SIZE": 150,
      "EXPERIMENTAL": true,
      "SKIP_VISITED_FORT_DURATION": 300,
      "SPIN_ALL_FORTS": true,
      "STAY_WITHIN_PROXIMITY": 3500,
      "MIN_ITEMS": {
        "ITEM_POTION": 10,
        "ITEM_SUPER_POTION": 10,
        "ITEM_HYPER_POTION": 10,
        "ITEM_MAX_POTION": 20,
        "ITEM_BLUK_BERRY": 10,
        "ITEM_NANAB_BERRY": 10,
        "ITEM_REVIVE": 10,
        "ITEM_MAX_REVIVE": 10,
        "ITEM_RAZZ_BERRY": 10
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 5,
        "WEEDLE":5, 
        "RATTATA":5,
        "DODUO":5 
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": ["MEWTWO","GYARADOS","MEW","DRAGONITE","LAPRAS","KANGASKHAN","MOLTRES","ZAPDOS","ARTICUNO","DITTO"],
      "THROW_POKEMON_NAMES": ["RATICATE","GOLDEEN","DODRIO","SPEAROW","MAGIKARP"],
      "MAX_CATCH_ATTEMPTS": 10,
      "LIST_POKEMON_BEFORE_CLEANUP": false,
      "LIST_INVENTORY_BEFORE_CLEANUP": true,
      "RELEASE_DUPLICATES": true,
      "RELEASE_DUPLICATES_MAX_LV": 1000,
      "RELEASE_DUPLICATES_SCALER": 0.9,
      "DEFINE_POKEMON_LV": "CP+IV"
    }
  ]
}
```

**Comment by j-e-k** [comment]
What he said

**Comment by playboz84** [comment]
Wow well you guys just made my life much much easier! thanks!
👍
