### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DirtyCajunRice** [j-e-k/poketrainer#155]
It would be nice to have a Pokeball priority with a buffer set up.

Right now if my bag maxes out on poke-balls then i no longer spin and miss out on potential ultra/great balls. If there could be an implementation that would allow a 10 space bag buffer (or self chosen) and a 
if bag_space < 10
  if item_poke_ball_count > min_item item_poke_ball 
   return

or however. that way it would hopefully eventually have you at all but min poke/great balls and maxed out on ultra balls!

**Comment by widget-** [comment]
I was thinking of suggesting something similar. It would be cool if you could specify something like "only carry 150 pokeballs of all types" and it'll toss any normal pokeballs if you already have 100 ultra balls and 50 great balls, etc.

**Comment by MePsyDuck** [comment]
I'm level 24 and I use these settings in config. This way I have potions and revives for gym battles and enough space left to store pokeballs.
`"MIN_ITEMS": {
         "ITEM_POTION": 5,
        "ITEM_SUPER_POTION": 5,
        "ITEM_HYPER_POTION": 50,
        "ITEM_MAX_POTION": 50,
        "ITEM_BLUK_BERRY": 10,
        "ITEM_NANAB_BERRY": 10,
        "ITEM_REVIVE": 20,
        "ITEM_MAX_REVIVE": 15,
        "ITEM_RAZZ_BERRY": 20,
		"ITEM_POKE_BALL": 5,
        "ITEM_GREAT_BALL": 100
      },`
Keep updating config as per your requirement, as for now until some dev implements your suggestions.

**Comment by j-e-k** [comment]
We have a basic version of this working, going to close this for now. Anything more complex is going to increase our feature bloat....
