### ISSUE TITLE
Max item Threshold

### ISSUE THREAD

**Issue by HibikiFox** [j-e-k/poketrainer#159]
So I haven't seen the option, but there needs to be a max item threshold, 

I ran the bot for a little bit and found that it will just horde items. I had 753/350 items at one point and no way to remove the extras without logging into a device...I would think that would be a massive red flag.

There should be an ability to set item maximums and it will junk the extras. 

If this exists please tell me that I missed it and where it is

**Comment by DavisMiculis** [comment]
You can specifiy how many items to keep in config.json
Here's example from one of my accounts:
```
            "MIN_ITEMS": {
                "ITEM_POKE_BALL": 50,
                "ITEM_POTION": 1,
                "ITEM_SUPER_POTION": 1,
                "ITEM_HYPER_POTION": 1,
                "ITEM_MAX_POTION": 1,
                "ITEM_BLUK_BERRY": 1,
                "ITEM_NANAB_BERRY": 1,
                "ITEM_REVIVE": 1,
                "ITEM_MAX_REVIVE": 1,
                "ITEM_RAZZ_BERRY": 1
            },
```

**Comment by HibikiFox** [comment]
That says Min Items, not Max.. .I had it configured the same way and it was still collecting massive ammounts
```

"MIN_ITEMS": {
        "ITEM_POTION": 10,
        "ITEM_SUPER_POTION": 10,
        "ITEM_HYPER_POTION": 10,
        "ITEM_MAX_POTION": 20,
        "ITEM_BLUK_BERRY": 10,
        "ITEM_NANAB_BERRY": 10,
        "ITEM_REVIVE": 10,
        "ITEM_MAX_REVIVE": 10,
        "ITEM_RAZZ_BERRY": 10
      },

I still ended up with 700+ items and way more than 10 of each of those specified here
```

**Comment by DavisMiculis** [comment]
Interesting, because it keeps me at the amount, which I've provided in the `MIN_ITEMS` list.

Here's fresh out of terminal log:
```
Player Items: PokeBalls: 52, GreatBalls: 195, MasterBalls: 0, UltraBalls: -1
 Potion: 1, Super Potion: 2, Max Potion 1, Hyper Potion 1
```

**Comment by HibikiFox** [comment]
-_- 

I will update my Dev and try, maybe that is the issue.

**Comment by HibikiFox** [comment]
updating the DEV indeed fixed it, Thank you!

**Comment by cod3b0t** [comment]
Not sure what happened but the bot fails to clear out the inventory, 

here is my config.json


```
      "MIN_ITEMS": {
            "ITEM_POKE_BALL": 50,
	    "ITEM_POTION": 1,
	    "ITEM_SUPER_POTION": 1,
	    "ITEM_HYPER_POTION": 1,
	    "ITEM_MAX_POTION": 1,
	    "ITEM_BLUK_BERRY": 1,
	    "ITEM_NANAB_BERRY": 1,
	    "ITEM_REVIVE": 1,
	    "ITEM_MAX_REVIVE": 1,
	    "ITEM_RAZZ_BERRY": 1
      }

```
```
2016-08-03 11:26:22,883 [    pgoapi] [ INFO] Player Items Before Cleanup: PokeBalls: 25, GreatBalls: 3, MasterBalls: 0, UltraBalls: 0 
 Potion: 106, Super Potion: 31, Max Potion 0, Hyper Potion 1, Lucky Eggs 0, Razz Berries 82
2016-08-03 11:26:22,883 [    pgoapi] [ INFO] Inventory has 351/350 items
2016-08-03 11:26:23,934 [    pgoapi] [ INFO] Player Inventory after cleanup: PokeBalls: 25, GreatBalls: 3, MasterBalls: 0, UltraBalls: 0 
 Potion: 106, Super Potion: 31, Max Potion 0, Hyper Potion 1, Lucky Eggs 0, Razz Berries 82

```

**Comment by rirze** [comment]
@cod3b0t Next time, please open a new issue for something like this. For this case, it seems you may have other items in your inventory that are taking up space. The bot doesn't list all the items in your inventory, so if you are able to login the app and clear out items from there, that's your best option. Otherwise you could try to guess what missing item from the logging is taking up space and try to set limits on that one item.

**Comment by cod3b0t** [comment]
@rirze appreciate it, that thought never crossed my mind.
