### ISSUE TITLE
[Suggestion] Average EXP/H

### ISSUE THREAD

**Issue by DavisMiculis** [j-e-k/poketrainer#160]
Would be an amazing feature to see average exp / hour, so you can keep track of what settings works the best, and just see in overall at what rate are you gaining exp.

Probably each time player profile data is requested, save EXP to object list with timestamp and exp then write a function that calculates hourly average, also you can get how much exp you've gained since script start.

If there's no better suggestions or overall response, I'll try my best at Python to add this feature :smile:  and create a pull request, else, please discuss, improve my proposal!

Also note on EXP - Could be interesting to see `(+99 EXP)` by each terminal message where particular activity gained you EXP. (Should also check if Lucky Egg is active?) EXP rewards table - http://www.serebii.net/pokemongo/trainer.shtml

**Comment by beeedy** [comment]
It would be nice to see some stats like this! Do you have the knowledge needed to implement this?

**Comment by DavisMiculis** [comment]
I will try to make work something basic and create a pull request tomorrow.

**Comment by DavisMiculis** [comment]
First basic calculations - https://github.com/j-e-k/poketrainer/pull/184

**Comment by j-e-k** [comment]
Closed by #184
