### ISSUE TITLE
codec can't encode character u'\xc9'

### ISSUE THREAD

**Issue by omlet05** [j-e-k/poketrainer#167]
2016-07-27 22:21:53,306 [   pokecli] [ERROR] Error in main loop, restarting 'ascii' codec can't encode character u'\xc9' in position 0: ordinal not in range(128)

do you ever notice this? I've got this everytime and get disconnected...

**Comment by j-e-k** [comment]
Does it work for you on develop?

**Comment by omlet05** [comment]
Is this when "EXPERIMENTAL": true is active? because it's set on true

**Comment by j-e-k** [comment]
I am talking about the develop branch of the repository

**Comment by omlet05** [comment]
Yes it's working, thanks a lot !

**Comment by CaM2091** [comment]
It appends when you rename a pokemon with a special character like É, À, Û...
For exemple, you renamed an Evee in Évee

**Comment by omlet05** [comment]
it's correct ! Thanks a lot, develop branch is running fine
