### ISSUE TITLE
RELEASE_DUPLICATES_MAX_LV clarity

### ISSUE THREAD

**Issue by Zyrixion** [j-e-k/poketrainer#168]
```
        elif self.RELEASE_DUPLICATES and (
                    self.pokemon_lvl(best_pokemon) * self.RELEASE_DUPLICATES_SCALER > self.pokemon_lvl(
                    pokemon) and pokemon.cp < self.RELEASE_DUPLICATES_MAX_LV):
            return True
```

Based on this code, shouldn't RELEASE_DUPLICATES_MAX_LV in config file be renamed to RELEASE_DUPLICATES_MAX_CP for clarity, since it's only releasing pokemon whose cp is under that value in the code?  Or, if it's not supposed to work like that, it's a bug report.

**Comment by Clintoxen** [comment]
If thats the new code then Level is defined as more than just CP

**Comment by j-e-k** [comment]
This needs to be clarified, LV can be various different constant, see: https://github.com/j-e-k/poketrainer/blob/master/pgoapi/pgoapi.py#L568

This needs to be added to the readme.....

**Comment by j-e-k** [comment]
paging @beeedy , I just fixed a bug in this, it should be `self.pokemon_level(pokemon)` rather than `pokemon.cp`....
right?

**Comment by beeedy** [comment]
Originally I had did not have LVL in the code, but when I implemented LVL in place of just CP I went through and converted all mentions of regular CP comparisons to LVL.... Clearly I missed one spot :P thanks to whoever found this!

**Comment by destiny117** [comment]
Closing this isse as the related code has changed quite a bit and the original issue is fixed since a while.
