### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by thatsweater** [j-e-k/poketrainer#173]
After setup and with all packages, Python 2.7 running debian, i get this error:

Traceback (most recent call last):
  File "pokecli.py", line 37, in <module>
    from pgoapi import PGoApi
  File "/home/pi/poketrainer-master/pgoapi/__init__.py", line 18, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/home/pi/poketrainer-master/pgoapi/pgoapi.py", line 48, in <module>
    from pgoapi.location import *
  File "/home/pi/poketrainer-master/pgoapi/location.py", line 7, in <module>
    from gmaps.directions import *
ImportError: No module named gmaps.directions

Unsure how to fix or proceed.

**Comment by sftwninja** [comment]
Ensure you've installed the required dependencies:
`pip install -r requirements.txt`

If you've already done that, would you mind posting the output of `pip freeze` so I can take a look?

**Comment by thatsweater** [comment]
Absolutely, and yes I have done that. Here is pip freeze:

chardet==2.3.0
colorama==0.3.2
expiringdict==1.1.3
future==0.15.2
geopy==1.11.0
gpiozero==1.2.0
gpsoauth==0.3.0
html5lib==0.999
lxkeymap==0.1
mcpi==0.1.1
ndg-httpsclient==0.3.2
numpy==1.8.2
picamera==1.10
pifacecommon==4.2.1
pifacedigitalio==3.1.0
pigpio==1.30
Pillow==2.6.1
protobuf==3.0.0b4
pyasn1==0.1.7
pycryptodomex==3.4.2
pygame==1.9.2a0
pygobject==3.14.0
pyOpenSSL==0.13.1
pyproj==1.8.9
pyserial==2.6
python-apt==0.9.3.12
requests==2.10.0
RPi.GPIO==0.6.2
RTIMULib==7.2.1
s2sphere==0.2.4
sense-hat==2.1.0
six==1.10.0
spidev==3.0
urllib3==1.9.1

**Comment by sftwninja** [comment]
Can you try running `pip install -U googlemaps` and try running the bot again?

**Comment by thatsweater** [comment]
Sure, and thank you. After running that i get the same error as the initial post.

**Comment by sftwninja** [comment]
Cool, sorry about that, my eyes skipped a line when I compared them. Try this
`pip install python-gmaps==0.3.1 Flask==0.11.1 Jinja2==2.7.1`

Then run the bot. If the bot comes up with the same error, could you post the output from that `pip` command?

**Comment by thatsweater** [comment]
My goodness it seems to be working, thank you ever so much. I've been fiddling with this thing for the past day and a half trying to figure it out on my own!

**Comment by j-e-k** [comment]
Glad you could get it working :)
