### ISSUE TITLE
How to correctly add pokemon to config to akways recycke a certain pokemoj?

### ISSUE THREAD

**Issue by freakyfreak87** [j-e-k/poketrainer#174]
Okay in the config i see an option for always release and theres pidgey in parametera, well any time i try and add a pokemon the,exact same way i consistenltly get json errors, im mainltly qanting to make sure the bot sells pokekon it evolves regardless of the keep if iv/cp is abive threshold.

**Comment by RikudouSage** [comment]
Can you send the config? Probably not a valid json.

**Comment by freakyfreak87** [comment]
` },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": ["MEWTWO"],
      "THROW_POKEMON_NAMES": ["PIDGEOTTO"],
      "MAX_CATCH_ATTEMPTS": 5
    },
`

this is the line i try and modify, ill put a comma after pidgey and put somthing like ["CHARMANDER"], after pidgey and always get a json error

**Comment by RikudouSage** [comment]
` "THROW_POKEMON_NAMES": ["PIDGEOTTO","CHARMANDER"]` - you don't add the whole `["CHARMANDER"]`, just add comma and then the name.

**Comment by freakyfreak87** [comment]
okay thanks lol, im new to this python thing but trying to just learn even configuring it lol, its appreciated, now if I input this, does it throw every single copy of that pokemon, or only ones caught while using bot?

**Comment by RikudouSage** [comment]
If the Pokémon is not in favorites or it isn't listed in "KEEP_POKEMON_NAMES" then it will be transfered.

**Comment by freakyfreak87** [comment]
okay, so as long as say one of the pokemon I have I want to keep, but toss others, as long as its favorited in game I dont risk losing that one copy.

**Comment by Clintoxen** [comment]
You can also do it like this 
`"MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_IDS":[
			4,
			5,
			6,
			9,
			7,
			25,
			37,
			38,
			66,
			67,
			68,
			77,
			78,
			97,
			103,
			107,
			114,
			130,
			131,
			133,
			134,
			135,
			136,
			137,
			147,
			148,
			149
         ],
      "THROW_POKEMON_IDS":[
            10,
            11,
            12,
            14,
            15,
            17,
            18,
            20,
			22,
			23,
			24,
			27,
			29,
			32,
			39,
			40,
			41,
			42,
			43,
			46,
			50,
			52,
			60,
			69,
			84,
			85,
			95,
			111,
			118,
			127
         ],`

**Comment by j-e-k** [comment]
Closing 😄
