### ISSUE TITLE
Could not catch pokemon:  status: -1

### ISSUE THREAD

**Issue by blazejp1337** [j-e-k/poketrainer#193]
What does "status: -1 means" ?

Almost every try to catch pokemon fails with this error msg

> 016-07-28 08:02:13,334 [    pgoapi] [ INFO] Catching Pokemon: Nickname: , Type:
>  Slowbro, CP: 1613, IV: 51.1111111111
> 2016-07-28 08:02:13,335 [    pgoapi] [ INFO] Attempting catch with ball type 1
> at 12.49 % chance. Try Number: 1
> 2016-07-28 08:02:17,601 [    pgoapi] [ INFO] Could not catch pokemon:  Nickname:
>  , Type: Slowbro, CP: 1613, IV: 51.1111111111
> 2016-07-28 08:02:17,601 [    pgoapi] [ INFO] Could not catch pokemon:  Nickname:
>  , Type: Slowbro, CP: 1613, IV: 51.1111111111, status: -1
> 2016-07-28 08:02:22,602 [    pgoapi] [ INFO] =================================
> 2016-07-28 08:02:22,602 [    pgoapi] [ INFO] On my way to the next fort! :) Trav

```




> 2016-07-28 07:59:07,276 [    pgoapi] [ INFO] Trying initiate catching Pokemon: N
> ickname: , Type: Pidgey, CP: 0, IV: 0.0
> 2016-07-28 07:59:07,548 [    pgoapi] [ INFO] Catching Pokemon: Nickname: , Type:
>  Pidgey, CP: 239, IV: 60.0
> 2016-07-28 07:59:07,549 [    pgoapi] [ INFO] Attempting catch with ball type 1
> at 40.01 % chance. Try Number: 1
> 2016-07-28 07:59:11,821 [    pgoapi] [ INFO] Could not catch pokemon:  Nickname:
>  , Type: Pidgey, CP: 239, IV: 60.0
> 2016-07-28 07:59:11,822 [    pgoapi] [ INFO] Could not catch pokemon:  Nickname:
>  , Type: Pidgey, CP: 239, IV: 60.0, status: -1
> 2016-07-28 07:59:18,822 [    pgoapi] [ INFO] =================================
> 2016-07-28 07:59:18,822 [    pgoapi] [ INFO] On my way to the next fort! :) Trav
> eled 874.03 meters of 874.03

**Comment by j-e-k** [comment]
Likely soft ban, try restarting in a bit

**Comment by sontek** [comment]
Yeah, I believe that is usually a softban which means you are probably walking too fast.  Shrink your step size.  At 6 I've never gotten a soft ban but I get them often above 30.  Haven't done much testing between those

**Comment by wesselvdv** [comment]
I just read somewhere that of you're softbanned, you can unsoftban yourself by having a gym fight. Anything we can create that does that?

**Comment by j-e-k** [comment]
I think that is just coincidental rather than a real fix from my exp

**Comment by wesselvdv** [comment]
@j-e-k check out this repo: https://github.com/earshel/PokeyPySnipe . 

It works like a charm. I was thinking we should at the option to snipe a pokemon from the web ui. However, we'll need a queue system for that.

**Comment by j-e-k** [comment]
I will try and get that implemented this weekend. Made a separate issue to track it #219
