### ISSUE TITLE
scaling IV and CP when combining

### ISSUE THREAD

**Issue by grobins** [j-e-k/poketrainer#197]
I see there are some options on combining CP and IV into a single metric to be assessed against a threshold.  Because CP is orders of magnitude above IV, combining them in the current way will give bias towards CP as the CP gets higher.

Instead can you scale CP against the max CP in the pokedex? Then allow a weighting when combining

So cpweighting * (CP / max(CP)) + 1 - cpweighting*IV

Then both CP and IV are in the range 0 to 1, and the resulting metric will be in the same range, which makes it easier to apply a threshold against.

**Comment by xezero** [comment]
I did exactly this in #188 :)

**Comment by grobins** [comment]
haha, i have to say i didn't see that.  Nice work!
