### ISSUE TITLE
How to solve this issue

### ISSUE THREAD

**Issue by loveinpin** [j-e-k/poketrainer#207]
2016-07-28 23:49:47,429 [    pgoapi] [ERROR] There were a problem responses for api call: False. Restarting!!!
Traceback (most recent call last):
  File "pokecli.py", line 129, in <module>
    main()
  File "pokecli.py", line 114, in main
    while not api.login(config["auth_service"], config["username"], config["password"]):
  File "/Users/StraDiVaRi/Desktop/dake2/poketrainer/pgoapi/pgoapi.py", line 819, in login
    response = self.heartbeat()
  File "/Users/StraDiVaRi/Desktop/dake2/poketrainer/pgoapi/pgoapi.py", line 211, in heartbeat
    raise AuthException("Token probably expired?")
pgoapi.exceptions.AuthException: Token probably expired?

**Comment by Jay1** [comment]
Servers are unstable currently, [click here](http://ispokemongodownornot.com/)

**Comment by j-e-k** [comment]
What he said

**Comment by disintonic** [comment]
I wanted to bring this issue to attention. I have four bots running and typically at least one of them does this every couple hours or so. Typically the bot won't start again, giving me the same error. To fix it I delete the auth_cache for that account and the next attempt works (I thought --cache was removed? Is it just coded to use auth_cache always now?).

If this does indeed fix it the error should be caught in the code, delete the auth file automatically, and restart the program.

**Comment by j-e-k** [comment]
I pushed a change to develop, let me know if that works for you

**Comment by loveinpin** [comment]
yeah  I think dev is working now, need more time to test it.
