### ISSUE TITLE
Error cant install protobuf3

### ISSUE THREAD

**Issue by panjitianda** [j-e-k/poketrainer#208]
when access pyton web.py
gettin
`Traceback (most recent call last):
  File "web.py", line 8, in <module>
    from pgoapi.poke_utils import *
  File "/var/www/test/poketrainer/pgoapi/__init__.py", line 16, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3`

when try to install it 

Installing collected packages: protobuf
  Found existing installation: protobuf 2.6.1
    Can't uninstall 'protobuf'. No files were found to uninstall.
Successfully installed protobuf

any info?

**Comment by HibikiFox** [comment]
You have PokemonGo-Map installed?

**Comment by panjitianda** [comment]
yes in install it before, read the recruitment for it, already uninstall it but i cant uninstall

**Comment by HibikiFox** [comment]
ok so there is an inconsistency between the requirements for PokemonGo-Map, and @j-e-k 's bot

if you `pip install -r requirements.txt` with PokemonGo-Map it will break @j-e-k 's bot

at least until you run `pip install -r requirements.txt` again for the bot.

that should fix it until something else is done to make the requirements not eat eachother

**Comment by panjitianda** [comment]
Fix it

reinstall the python completely, the protobuf 2.6.1 is cached and i cant uninstall it or upgrade

after reinstall python i upgrade all, thanks for it
