### ISSUE TITLE
Error cant install pyproj

### ISSUE THREAD

**Issue by Readdeo** [j-e-k/poketrainer#209]
I cannot install pyproj, i tried it manually from github zip, and with the pip install command, the result is always this:

    building 'pyproj._proj' extension
    error: [Error 2] A rendszer nem találja a megadott fájlt

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\readdeo\\appdata\\local\\temp\\pip-build-1xvxhh\\pyproj\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\readdeo\appdata\local\temp\pip-gir5rf-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\readdeo\appdata\local\temp\pip-build-1xvxhh\pyproj\

Can you please help me?

**Comment by HibikiFox** [comment]
See issue #208 

Or you need to install Microsoft C++ compiler for Python 2.7

**Comment by destiny117** [comment]
For reference: https://www.microsoft.com/en-us/download/details.aspx?id=44266

Closing.
