### ISSUE TITLE
Multi Acccount broken?

### ISSUE THREAD

**Issue by Clintoxen** [j-e-k/poketrainer#211]
For some reason I cant get `python pokecli.py -i 0 1 2` to work anymore on the newest build, looks like I have to open multiple command promts to have multibot going now? 

`
C:\Users\clinton\Documents\SourceTree\poketrainer>python pokecli.py -i 0 1 2
usage: pokecli.py [-h] [-i CONFIG_INDEX] [-l LOCATION] [-d]
pokecli.py: error: unrecognized arguments: 1 2
`

**Comment by j-e-k** [comment]
Instead you have to run them in separate terminals (again). 
For a quick bash script:
```
stty -tostop; for i in `seq 0 2`; do python pokecly.py -i $i & done
```

**Comment by j-e-k** [comment]
(or as someone on slack said worked for them):
```
stty tostop; for i in {0..2}; do python pokecli.py -i $i; done
```

**Comment by Clintoxen** [comment]
alright thanks @j-e-k

**Comment by Clintoxen** [comment]
@j-e-k also the readme and wiki will need to be updated unless this is temp
