### ISSUE TITLE
no module named 'md5'

### ISSUE THREAD

**Issue by vanucci** [j-e-k/poketrainer#220]
Im getting this error, when running the requirements.txt 
googled, but nothing i can see clearly gives an answer. I am new to this also. 

```
Collecting expiringdict==1.1.3 (from -r requirements.txt (line 10))
  Using cached expiringdict-1.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kyz69dm3/expiringdict/setup.py", line 2, in <module>
        import md5  # fix for "No module named _md5" error
    ImportError: No module named 'md5'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kyz69dm3/expiringdict/

```

**Comment by loveinpin** [comment]
I have same problem with Win 10, thought error is that  setuptools not installed.
go web download it then try this 
`pip install --upgrade setup tools `
make sure  ez_setup is exist then 
`pip install ez_setup`

its work on me

**Comment by vanucci** [comment]
still having the issue, im on ubuntu

**Comment by j-e-k** [comment]
What version of python are you using?

**Comment by vanucci** [comment]
3.5

**Comment by sftwninja** [comment]
@vanucci At the moment, one of the dependencies, `expiringdict` does not support Python 3. In the meantime, please use Python 2.7.11 or 2.7.12.

**Comment by j-e-k** [comment]
Python 3 support is going to take some time. For now use pyenv to use python 2.7 for this project.

Thanks 😄
