### ISSUE TITLE
The given key has gone over the requests limit

### ISSUE THREAD

**Issue by joshpalan** [j-e-k/poketrainer#226]
I can no longer run pokecli.py. When I try to run I get the following error:

```
Traceback (most recent call last):
  File "pokecli.py", line 129, in <module>
    main()
  File "pokecli.py", line 104, in main
    position = get_pos_by_name(config["location"])
  File "pokecli.py", line 50, in get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "/usr/local/lib/python2.7/site-packages/geopy/geocoders/googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/usr/local/lib/python2.7/site-packages/geopy/geocoders/googlev3.py", line 338, in _parse_json
    self._check_status(page.get('status'))
  File "/usr/local/lib/python2.7/site-packages/geopy/geocoders/googlev3.py", line 363, in _check_status
    'The given key has gone over the requests limit in the 24'
geopy.exc.GeocoderQuotaExceeded: The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.
```

I tried uninstalling and reinstalling all pip packages listed in requirements, I've tried deleting and rebuilding the repo, nothing has worked.

**Comment by jolbol1** [comment]
May be your google API key has gone over the limit, It has a cap of 2500 requests a day.

**Comment by joshpalan** [comment]
This happens whether I have a google maps API key set or not. If I log into my google API dashboard, I can see zero requests have been made. :/

**Comment by HibikiFox** [comment]
I would say Generate a New key, be sure it is a SERVER key, and try that

**Comment by joshpalan** [comment]
I generated a new SERVER key, set it in the config, saved and tried it again. Same error.

**Comment by j-e-k** [comment]
This is an error caused by geopy when geocoding your starting location, there are two options for us to fix this:

allow users to specify a key to google for geocoding
(and/or)
allow users to enter starting location as lat,lng

**Comment by joshpalan** [comment]
Any workaround in the mean time?

**Comment by j-e-k** [comment]
on line 104 in pokecli.py where you see:

`    position = get_pos_by_name(config["location"])`

change it to:
`    position = (lat,lng,alt)` 
with those being the starting coordinates

**Comment by joshpalan** [comment]
You rock. Thanks my man!
