### ISSUE TITLE
Cannot use Google Auth with 2FA enabled.

### ISSUE THREAD

**Issue by BigMacStorm** [j-e-k/poketrainer#232]
I attempted to log in with both my own computer and a freshly created AWS instance, both continued to fail authenticating over several hours of different attempts. During this time my phone was able to log in with no issues and PTC worked fine in poketrainer. Once I disabled 2FA it instantly began working.

**Comment by joychugh** [comment]
to use Google Auth with 2FA, create an application password under accounts security option.
