### ISSUE TITLE
Clarifying some Config settings.

### ISSUE THREAD

**Issue by charredchar** [j-e-k/poketrainer#233]
First, I thank you so much for updating the readme and expanding on some of the added options. But some of it still seems a little confusing.

What exactly does the number represent after the name under POKEMON_EVOLUTION?

RELEASE_DUPLICATES_MAX_LV. I originally thought it was based off what you set DEFINE_POKEMON_LV to, so if it was IV than it would be a percent of 100 or if it was CP it would be the actual CP value. Now am I not completely sure since lvl in now in the output. Though I am honestly confused with all of the lvls and how they are actually calculated but that is different subject.

**Comment by beeedy** [comment]
number after name in POKEMON_EVOLUTION is how many candies are needed to evolve. PERSONALLY I see no reason these shouldn't be hard coded, there is no reason there can't just be a dictionary hidden away :P 

LVL's are a hotly debated topic and hopefully I can clear up some confusion as I worked on the system that is currently in place. LVL's are just a layer of abstraction between multiple pokemon metrics and the rest of the transfer system. You can define lvl to be whatever you want, such as CP, IV, CP*IV, or CP+IV (there are others, but not sure if they are pulled in atm). When you define a pokemon's lvl, that lvl is what is used to compare two pokemon to determine which is the stronger (keep) and which is the weaker (transfer). RELEASE_DUPLICATES_MAX_LV is a hard limit to the highest lvl that will be discarded. I have also seen lvl in the output, and it does not correlate with how the lvl system should be working. I will look into what that is actually printing....

**Comment by charredchar** [comment]
I figured the number of candies were hard coded since it evolves all when it can. But I do actually see a use of having the configurable POKEMON_EVOLUTION, it is a lot like having MIN_ITEMS, a way to keep a few candies if you want to use them to level up later. Thanks for clarifying this one. It would be nice if there was a way to hold off evolution until a set point though, ie "Use Lucky Egg, Evolve when you have X+ Pokemon type and Y+ Candy"

I personally don't see a point of a Pokemon's "level" in Go as it does not seem they have a real cap beyond the player level with is subject to change. Of course, CP*IV, or CP+IV are not numbers that are output so I can understand wanting to add that for easier comparison but I think "level" should go away all together. And as far as I can tell the only metric that actually matters when comparing two of the same types is the IV, much like the games they are how "perfect" you can gets the stats of a giving Pokemon and since CP can raise with more candy and only halted by your player level that becomes a useless comparison too. (I haven't done this now that I think about it, I will test it later on today, maxing out two Pokemon with the same IV and see if their CP matches.)

**Comment by Jay1** [comment]
level is confusing, because it's actually a thing in PokemonGo  and someone repurposed it in the bot

http://pokemongo.gamepress.gg/power-up-costs

usually you power up the pokemon 1-2 times to discover his level in that board, then you compare it to his potential Pokemon Min/Max CP Values which you can find [here](http://pokemongo.gamepress.gg/pokemon/149)   for Dragonite if you scroll down a bit.

Moveset is certainly the main priority. Then you want to check potantial  min/max CP value and finally IV.  The current CP when you catch the pokemon is not important since the bot can farm hundred thousands of stardust in a couple hours. If a level 19 dratini is at 95% of his max potential CP (506 CP out  of 533 MAX) you want to keep it   Let's keep that dratini as an exemple.   That level 19 dratini 95% potential CP at level 40 will reach 3325 CP (in his Dragonite evolution).

**Comment by charredchar** [comment]
@Jay1, I love you for going in depth with that.

But that all pretty much comes to the same point I was making, why bother with Level at all when we can see the IV % and the CP? And as I mentioned there is no real level in Go to start with, as you mentioned only CP is seen. @beeedy, I can see why this topic is so hotly debated.

**Comment by beeedy** [comment]
@charredchar, there have been many discussions about the 'best way' to compare two pokemon and it seems everyone has a different opinion. Some prefer to just compare straight CP as it gives more of an instant gratification and is an obvious visual when seen in the app. Some like to compare only IV as in the long run it gives you the strongest pokemon. Some more are working on more complex methods to try and compare some, which I believe is denounced as lvl "Fancy" now. Personally I prefer to use CP+IV for sorting as it gives a form of instant gratification you see with CP while also keeping based off of IV for the long term strength. It is all preference, and I think we have all just agreed to disagree and hopefully the system in place lets us all live in peace :P

**Comment by xezero** [comment]
@Jay1 It's actually only partially true that two Pokemon with the same IV will have the same max CP. 
IV% is derived by an equal weight in the individual attack, stamina, and defense, while CP's calculation is much more affected by the attack stat over the others. So I have found that even though two of the same type of Pokemon have the same IV%, their max CP is different depending on the different allocation between the three stats.

Nonetheless, IV% is still a great indication of a Pokemon's max potential :)

**Comment by charredchar** [comment]
@xezero Thank you for that bit of information. I did not actually think of that before but that is partly because my goal is to have all of my Pokemon at IV 100 so in the end CP doesn't matter much to me. But knowing that does help me with decisions when configuring who to release.

**Comment by destiny117** [comment]
Closing for now, open a new Issue if you need further help / clarification.
