### ISSUE TITLE
Google map API issues

### ISSUE THREAD

**Issue by kriswong** [j-e-k/poketrainer#238]
So not really sure how to solve this but running this poketrainer on 5 accounts (PTC) causes the API quota to be used. I was wondering if it is possible to limit the GoogleMap API or if it is preferrable to just use GMAIL acct to get APIs?

Thanks

**Comment by sftwninja** [comment]
So, you can totally create multiple apps in your Google API Console dashboard, and they all have separate quotas. (At least for me, and I do have a business account) I believe they all get the 2,500 free calls per day.

The bot really needs that info to build believable routing, but I think in the future I'd like to get some effort in on working on maybe using something like [WTracks/GPX](https://wtracks.appspot.com/) to sidestep the whole GoogleMap API calls and costs.

So, short answer, no, I don't believe so at the time being. Long answer, is in the future it'd be nice to branch off into other solutions that don't require costs or spamming the Google Maps API every heartbeat.

**Comment by beeedy** [comment]
My 2c, I have been running for days now with Google disabled and have hit no problems

**Comment by j-e-k** [comment]
I am not using google atm either, I think if we were going to get banned it would be for far easier things to detect than gps....

**Comment by beeedy** [comment]
> I am not using google atm either, I think if we were going to get banned it would be for far easier things to detect than gps....

could not agree more. I have thought about injecting noise into the path, or sigmoids, to make it less obvious I am walking directing from pokestop to pokestop. To be honest though, I think there are many other red flags they could use to catch us :P

**Comment by sftwninja** [comment]
Count me paranoid, I like looking like I'm a player that follows all traffic laws (and plays Pokemon GO for 145 hours straight :P)

**Comment by opoto** [comment]
Please don't use WTracks for this, Pokemon Go users are overloading this server which is now blocked because of exceeded hosting quotas. 
Thanks

**Comment by sftwninja** [comment]
@opoto the beauty of WTracks is that it generates a pathing file that doesn't require constant request/response with a service. I'm sorry WTracks is down, and that they accidentally got super popular with GO, but their format and service fits the bill here for a really good incidental pathing tool.

**Comment by opoto** [comment]
I'm the WTracks owner, and the generated traffic doesn't fit my bill ;)

**Comment by sftwninja** [comment]
@opoto Hello there, WTracks owner, you make a really nifty tool that accidentally was pretty perfect :P 

I found your repo [here](https://github.com/opoto/wtracks), is it cool if we host our own private instances to generate paths with?

**Comment by opoto** [comment]
That would be OK for me. I'm not sure datastore and login features are easily portable. NecroBot is looking at the same option, maybe you can join your efforts.

**Comment by opoto** [comment]
I added a "donate" button to WTracks. I will use potential revenue to pay for additional hosting quotas.

**Comment by destiny117** [comment]
Closing this for now.

@sftwninja if you happen to integrate WTracks without a private instance, make sure to update the readme pointing users to their page and request to donate if possible.
