### ISSUE TITLE
Unexpected HTTP server response 502

### ISSUE THREAD

**Issue by charredchar** [j-e-k/poketrainer#239]
I've seen this pop up before, it will happen randomly if I leave the bot running for awhile. It does not seem to happen at any specific point, this time was right after a distance message, it reconnected within 30 seconds.

> 2016-07-28 21:15:59,822 [   rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
> 2016-07-28 21:15:59,828 [   pokecli] [ERROR] Error in main loop, restarting %s
> Traceback (most recent call last):
>   File "C:\Users\Char\Desktop\poketrainer-develop\pokecli.py", line 121, in main
>     api.main_loop()
>   File "C:\Users\Char\Desktop\poketrainer-develop\pgoapi\pgoapi.py", line 947, in main_loop
>     self.spin_near_fort()
>   File "C:\Users\Char\Desktop\poketrainer-develop\pgoapi\pgoapi.py", line 501, in spin_near_fort
>     self.walk_to_fort(fort_data)
>   File "C:\Users\Char\Desktop\poketrainer-develop\pgoapi\pgoapi.py", line 484, in walk_to_fort
>     self.fort_search_pgoapi(fort, self.get_position(), fort_data[1])
>   File "C:\Users\Char\Desktop\poketrainer-develop\pgoapi\pgoapi.py", line 428, in fort_search_pgoapi
>     player_longitude=player_postion[1]).call()['responses']['FORT_SEARCH']
> TypeError: 'bool' object has no attribute '__getitem__'

**Comment by Jay1** [comment]
We had that problem a lot July 28 and I think it's related to unstable PoGo servers. I run quite a few debugger tools and that's the only explanation I could find so far. Maybe someone will find something else down the road...

**Comment by charredchar** [comment]
I figured it might be something related to that considering it seems to be so random and reconnects perfectly fine. Not to mention "Unexpected HTTP server response - needs 200 got 502" sounds like a connection error or some sort that might not be related to the bot itself. I'm not sure if there is a way to program in error codes or anything, such as making the bot output something along the lines of "Connection Error (code): Reconnecting." instead of some random response so we know it is not some other issue.

**Comment by destiny117** [comment]
Known occasional server issues. Closing this.
