### ISSUE TITLE
Add Power up/Transfering/Evolving to web API

### ISSUE THREAD

**Issue by j-e-k** [j-e-k/poketrainer#24]
Clean up internally to allow the web api to communicate with the bot.

**Comment by joychugh** [comment]
👍

**Comment by joychugh** [comment]
I will move out the evolve pokemon from evolve all pokemon method to make it easier for you to use it in the web interface. Also we may want to lock the evolve method, to make sure that if there is an auto evolve going on, web api should wait till its finished to call the evolve.

**Comment by wesselvdv** [comment]
How does the Web API work exactly? I don't see anything that looks like a way to interact with pgoapi interactively? REST or something? If you guys expose a proper REST api, then I can build a simple angular app against it.

**Comment by j-e-k** [comment]
Right now the web api is uber simple. It just loads the data the bot dumps periodically. Need to handle the sleeps differently in the bot in order to actually send messages to it....

**Comment by wesselvdv** [comment]
That would be very nice! Best thing is to put it into the heartbeat, and using something like this would be so awesome:

https://github.com/miguelgrinberg/python-socketio

**Comment by PDenzinger** [comment]
Slightly off topic, but a an event or request queue populated from the web interface would be very useful to implement other commands as well. Changing movement speeds, setting a walk destination (to choose new origin, walk at normal speed to that destination, instead of closing/opening). Possibilities are endless.

**Comment by FendleTruck** [comment]
This would open the door to a lot of nice things. For example it'd be great to be able to change the "origin" location while running, and have the bot walk/run there before continuing to pillage forts.

**Comment by j-e-k** [comment]
Development has the base for this feature. Closing this to consolidate further web.py work in its own issue
