### ISSUE TITLE
[Feature request] Store last coordinates on crash, resume at that position

### ISSUE THREAD

**Issue by UnacceptableUse** [j-e-k/poketrainer#241]
It would be nice if the current location could be saved and reloaded on restart/crash, I'd love to see how far away it roams on it's own, but it keeps crashing and ending up back at where I started it.

**Comment by beeedy** [comment]
I completely agree. It has also been raised that this is essentially asking for a soft ban. Is someone working on this? It really should not be too difficult to implement and I could take a stab

**Comment by joychugh** [comment]
@beeedy if you like to, please go ahead. I have some ideas in mind, like using a state file updated every heartbeat and maintaining a state class and we can just pickle the object on the file system and when we restart un-pickle it (only when the restart was due to an error).

**Comment by beeedy** [comment]
I like the idea of just pickling the object on each heartbeat and un-pickle if the bot went down from a crash. Will look into this over the weekend, but may not have time. If someone else is interested in taking this on please just let me know

**Comment by j-e-k** [comment]
I can put together a quick hack using the data dump, give me a few minutes

**Comment by j-e-k** [comment]
Should work 😄
