### ISSUE TITLE
On develop branch "python pokecli.py" does nothing

### ISSUE THREAD

**Issue by adrianocr** [j-e-k/poketrainer#242]
`python pokecli.py` doesn't do anything on latest dev pull. Just no error, nothing.

**Comment by charredchar** [comment]
I had this happen also until I redid my config file. Re-create yours using the latest example to see if this helps. It is a practice I have been getting use to doing with every release as new things keeps getting added but cause problems if they are missing from the config.

**Comment by adrianocr** [comment]
@charredchar that did the trick, thanks! Weird issue. I would at least expect to see an error.
