### ISSUE TITLE
Ball difficulty by capture difficulty doesn't seem to work.

### ISSUE THREAD

**Issue by venounan** [j-e-k/poketrainer#243]
Came by a dragonite today, it used two regular pokeballs and no raspberries. Is it possible to adjust this?

**Comment by joychugh** [comment]
hmm, usually pokemons don't flee in 2 runs, esp if their probability is more than 30% 
can you post the pokemon stats?

**Comment by joychugh** [comment]
we have raspberry feature in develop but not in master yet.

**Comment by venounan** [comment]
It was a 2000cp Dragonite, the catch percent i think was only like 6.7%, and it ran after throwing one ball. The code said ball type 1 which I assume was normal pokeballs, but I have seen in the past it throwing ball type 3 for other rare types, which I'm assuming are ultraballs.

**Comment by joychugh** [comment]
I will see if i can improve this mechanism already an issue opened for this.

**Comment by venounan** [comment]
I got status -1 and after doing some more research it seems I was probably soft banned when I tried to catch this pokemon, so this might be working as intended.
