### ISSUE TITLE
Accessing Web UI

### ISSUE THREAD

**Issue by beeedy** [j-e-k/poketrainer#244]
In the dev branch, what is the proper way to now setup and access the web UI? I know it has been seeing some much appreciated TLC recently but I can no longer seem to run web.py and it does not appear pokeclient.py has it built in (which I believe it may have in a previous build...). If it is of any use, here is the dump from running web.py

```
Traceback (most recent call last):
  File "web.py", line 64, in <module>
    app.run(host='0.0.0.0',debug=True)
  File "/home/broderick/.local/lib/python2.7/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/home/broderick/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 677, in run_simple
    s.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

```

**Comment by sftwninja** [comment]
Are you on Windows or Linux/BSD/Mac? Looks like something's running on that port and we just need to find it.

**Comment by beeedy** [comment]
Ubuntu 14.04, That is what I had also thought but I was unable to find anything running. Trying to access the ip/port just causes a browser to time out

**Comment by sftwninja** [comment]
Can you post the output of `lsof -i :5000`?

**Comment by beeedy** [comment]
```
COMMAND   PID      USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
python  13861 XXXXXXXX    5u  IPv4 1642264      0t0  TCP *:5000 (LISTEN)

```
So it does appear there is a python server running somewhere

**Comment by sftwninja** [comment]
eyyyy, so there is something listening on that port.

Should be able to kill it with `kill -9 13861`

**Comment by beeedy** [comment]
That seems to have fixed it! Thanks for the help, still just getting my feet wet with linux
