### ISSUE TITLE
Can't access WebUI with level 1 account

### ISSUE THREAD

**Issue by MRokas** [j-e-k/poketrainer#248]
It throws this, since .json has no prev_level_exp key:

KeyError

KeyError: 'prev_level_xp'
Traceback (most recent call last)

    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__

     [Open an interactive python shell in this frame] return self.wsgi_app(environ, start_response)

    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app

    response = self.make_response(self.handle_exception(e))

    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/*/python/test/web.py", line 58, in inventory

    player['level_xp'] = player['experience']-player['prev_level_xp']

    KeyError: 'prev_level_xp'

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

**Comment by xthedeus** [comment]
This should be fixed by replacing the following line https://github.com/j-e-k/poketrainer/blob/master/web.py#L58 :
`player['level_xp'] = player['experience']-player['prev_level_xp']`
with below:
`player['level_xp'] = player['experience']-player.get("prev_level_xp",0)`

**Comment by albertonoys** [comment]
You are on master, right? the fix @xthedeus is talking about was already merged to the develop branch here: https://github.com/j-e-k/poketrainer/commit/edf80394505ccf91c991a0c08029977042912a0a

**Comment by xthedeus** [comment]
@albertonoys - Ah right, I just made my first PR including this fix from the master to the dev... need moar coffee... https://github.com/j-e-k/poketrainer/pull/255

**Comment by albertonoys** [comment]
@xthedeus Hey, don't sweat it, my first PR ever was yesterday so... but yup, make sure you are branching from an updated develop branch and there shouldn't be any conflicts.

**Comment by MRokas** [comment]
Yeah, I'm on master.

> make sure you are branching from an updated develop branch

Kinda funny, master is supposed to be stable, not develop.. :D

**Comment by albertonoys** [comment]
@MRokas I meant that if @xthedeus is going ask for a PR, as all PRs should be submitted to the develop branch, he should be branching from the develop branch. 

But I get what you mean, I think that because almost everyone here is working on something, all the testing is being done in develop. 

@joychugh, if you could merge https://github.com/j-e-k/poketrainer/commit/edf80394505ccf91c991a0c08029977042912a0a in master, that would be great :D

**Comment by j-e-k** [comment]
Done 😄
