### ISSUE TITLE
ImportError: No module named zerorpc

### ISSUE THREAD

**Issue by DeOrthodox** [j-e-k/poketrainer#249]
Traceback (most recent call last):
  File "pokecli.py", line 37, in <module>
    import zerorpc
ImportError: No module named zerorpc

i get the same on the WEB.PY but with import gevent

**Comment by schmuff** [comment]
try running "pip install -r requirements.txt" again. It solved it for me

**Comment by DeOrthodox** [comment]
thank you that fixed it!
