### ISSUE TITLE
Issue after updating

### ISSUE THREAD

**Issue by lordskylare** [j-e-k/poketrainer#252]
before i updated everything was working fine

```
Traceback (most recent call last):
  File "pokecli.py", line 129, in <module>
    main()
  File "pokecli.py", line 95, in main
    config = init_config()
  File "pokecli.py", line 65, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by MRokas** [comment]
It failed to load `config.json` file

**Comment by beeedy** [comment]
For some reason there seems to be a rogue bug that makes it so you must recreate the config after each update. I would hope/assume someone is looking into this....

**Comment by venounan** [comment]
I'm having an issue when I edit anything with " in the config file it changes it to the text-type of " which is curly. That breaks the JSON. Try taking your config code and pasting it in here: http://jsonlint.com/ and see if there are any errors.

**Comment by lordskylare** [comment]
I downloaded new config File and configured it and it worked, thanks.

**Comment by venounan** [comment]
Also when you make the config file, just duplicate config.json.example before you edit it. That way you always will have a clean version. And the quotes thing can be remedied by copy and pasting them from another section of the JSON file if that was indeed your issue.
