### ISSUE TITLE
[Question] how to append "KEEP_POKEMON_NAMES"?

### ISSUE THREAD

**Issue by q32103940** [j-e-k/poketrainer#253]
> "KEEP_POKEMON_NAMES": ["MEWTWO"],

I can't get the syntax right. How do I add pokemons to the list? I keep getting json load errors

**Comment by MrHalfman** [comment]
Just add them to the array in capitalized letters.

Like `"KEEP_POKEMON_NAMES": ["MEWTWO", "PIKACHU"],`

**Comment by q32103940** [comment]
thanks, sir!
