### ISSUE TITLE
Bot keeps low CP pokemons

### ISSUE THREAD

**Issue by blazejp1337** [j-e-k/poketrainer#256]
Im just wondering should I enable "release_duplicates' if i dont want to collect low CP/IV pokemons?

My settings looks like that:

```
      "KEEP_CP_OVER": 350,
      "KEEP_IV_OVER": 65,
```

```
      "POKEMON_EVOLUTION": {
        "WEEDLE":12
```

`      "MIN_KEEP_IV": 65`

and take a look at how my bag looks like

> Nickname: , Type: Weedle, CP: 14, IV: 20.0
> Nickname: , Type: Drowzee, CP: 14, IV: 75.5555555556
> Nickname: , Type: Drowzee, CP: 12, IV: 35.5555555556
> Nickname: , Type: Paras, CP: 11, IV: 64.4444444444
> Nickname: , Type: Weedle, CP: 10, IV: 17.7777777778
> Nickname: , Type: Weedle, CP: 10, IV: 37.7777777778
> Nickname: , Type: Weedle, CP: 10, IV: 37.7777777778
> Nickname: , Type: Krabby, CP: 10, IV: 48.8888888889
> Nickname: , Type: Rattata, CP: 10, IV: 51.1111111111

Why isnt it transfering pokemons below CP 350 and IV 65 ? 
Also pokemon evolutions doesnt seems to be working

**Comment by beeedy** [comment]
release_duplicates will remove them, but please make sure you fully understand how the feature works to avoid unwanted loss of other pokemon!

**Comment by HibikiFox** [comment]
Also you have IV over 65.. it checks both, if you have it set to keep CP of 1000+ but a low IV it will keep a pokemon that meet at least ONE of the 2 settings.

**Comment by venounan** [comment]
So if I were to have:

> "MIN_SIMILAR_POKEMON": 4,
      "KEEP_POKEMON_NAMES": ["TAUROS"],
      "THROW_POKEMON_NAMES": [],
      "LIST_POKEMON_BEFORE_CLEANUP": true,
      "LIST_INVENTORY_BEFORE_CLEANUP": true,
      "MAX_CATCH_ATTEMPTS": 10,
      "RELEASE_DUPLICATES": true,
      "RELEASE_DUPLICATES_MAX_LV": 70,
      "RELEASE_DUPLICATES_SCALER": 0.9,
      "DEFINE_POKEMON_LV": "IV"

It would keep a minimum of 4 of each pokemon, keep all Tauros, release any duplicates over 4 with an IV value of under 70%?

**Comment by beeedy** [comment]
I would have to look back through the code, but I BELIEVE that when you enable RELEASE_DUPLICATES it ignores  KEEP_CP_OVER and KEEP_IV_OVER. Otherwise you are pretty much spot on. The only other thing (which is a default and really shouldn't be) is RELEASE_DUPLICATES_SCALER. You probably should just set this to 1.0. Right now it defines a secondary "RELEASE_DUPLICATES_MAX_LV" that is the equivelent of your highest IV for a specific pokemon * 0.9. That feature is a little confusing and is really only useful if you want the bot to keep pokemon if they are close in lvl, but maybe not high enough to where they should be released. Long story short, set RELEASE_DUPLICATES_SCALER to 1.0 unless you want it otherwise

**Comment by TheWayAway** [comment]
My settings are the following, but it's not releasing any pokemon.

```
      "KEEP_CP_OVER": 950,
      "KEEP_IV_OVER": 80,

      "MIN_SIMILAR_POKEMON": 2,
      "KEEP_POKEMON_NAMES": ["MEWTWO"],
      "THROW_POKEMON_NAMES": ["PIDGEY"],
      "LIST_POKEMON_BEFORE_CLEANUP": true,
      "LIST_INVENTORY_BEFORE_CLEANUP": true,
      "MAX_CATCH_ATTEMPTS": 10,
      "RELEASE_DUPLICATES": true,
      "RELEASE_DUPLICATES_MAX_LV": 1000,
      "RELEASE_DUPLICATES_SCALER": 1.0,
      "DEFINE_POKEMON_LV": "CP"
    },

"MIN_KEEP_IV": 70
```
If someone can help me with this, it'll be greatly appreciated!

Thanks

**Comment by blazejp1337** [comment]
Me either also

After few hours my bag is getting full again..

**Comment by destiny117** [comment]
Please check the new readme for current configuration options on this. Closing this. If you need further help open a new Issue please.
