### ISSUE TITLE
Feature request: GoGetIt

### ISSUE THREAD

**Issue by JustAnotherScriptKiddie** [j-e-k/poketrainer#261]
Would there be a way to push coords to the script that would walk your character to a specific place?  I like to check out Pokevision from time to time for specific Pokes, and when I find one, I'll stop the script, change config.json starting location, and restart the bot after an appropriate time.

If there were a way to push coords to the script, and have your character change course (bump up travel speed and ignore stops & Pokes along the way) , catch Pokes within a radius of your given coords, return (speed up & ignore again) to where they were, and resume operations, I think that would be fuckin boss.

I'd be able to grind out my Magikarp farm (keep getting bad gyrados movesets!) and still chase after desirable targets without all the logout, change config, wait... wait... wait... restart. Just to do it again when there's nothing in my area, and I go back to farming.

**Comment by venounan** [comment]
It would be awesome if we could make a list of pokes that take priority, and if they can reach it by the time the timer runs down the bot will head there and get it. That sort of creates the "traveling salesman" problem though - if the bot can only reach one of two in time which does it go for? Does it try and make a route from poke to poke?

**Comment by xezero** [comment]
We could probably incorporate this code (Pokevision uses this API) https://github.com/AHAAAAAAA/PokemonGo-Map

into our bot and perhaps scan a large area around where the bot currently is and prioritize walking towards pokemon that aren't in your pokedex and/or specified priority targets in the config file like mentioned above.

**Comment by teh3vil** [comment]
I'm interested in seeing an array option for the locations in config, being able to set a couple of known good spots myself would be a great. Perhaps if we utilise "walk_to_origin" and feed it an array item every time it's called instead of the actual origin point, we could get it to wander over to your other places, initiating a run there, then wandering over to the next one etc etc

I'll look into this later...

**Comment by stolencatkarma** [comment]
you can set -L "lat, long" from the command line and it will override the config.
