### ISSUE TITLE
Web.py Error: There is no bot running with the input username!

### ISSUE THREAD

**Issue by xezero** [j-e-k/poketrainer#267]
I'm running two bots and only the last one to be run can be displayed in the web page. My other bot's page displays "There is no bot running with the input username!".

Did something change to not allow multiple bots to be displayed?

**Comment by j-e-k** [comment]
this is a bug, give me a moment

**Comment by j-e-k** [comment]
sorry about that!

**Comment by xezero** [comment]
Thanks for the quick fix! :)
