### ISSUE TITLE
latest dev branch requires location in terminal

### ISSUE THREAD

**Issue by dannydotco** [j-e-k/poketrainer#270]
```
$ python pokecli.py -i 0
usage: pokecli.py [-h] [-i CONFIG_INDEX] -l LOCATION [-d]
pokecli.py: error: argument -l/--location is required
```

I've specified the location in the `config.json` so it shouldn't be a requirement in the terminal.

**Comment by Jay1** [comment]
Err I think you forgot to rename config.json.exemple to config.json

**Comment by dannydotco** [comment]
... really?

Have some respect, dude.

I have been debugging it.

`location: { address: 'string' }` has been changed to just be `location: 'string'` and it cannot live in `defaults` right now.

**Comment by j-e-k** [comment]
Just fixed it I think...

**Comment by Jay1** [comment]
I don't think it was disrespect...  you get this kind of output from terminal when you forget to rename. With so little information you gave me that's all I could think of
