### ISSUE TITLE
Can You Update Your Previous Github Pull Without Having To Download the whole Repo?

### ISSUE THREAD

**Issue by freakyfreak87** [j-e-k/poketrainer#275]
Im relatively new to github, and I was wondering if theres a way to just update preexisting file i've previously downloading instead of redownloading the whole repo again/

**Comment by mdjong1** [comment]
https://www.sourcetreeapp.com/

**Comment by sftwninja** [comment]
If you've `git clone`'d the repo, you should be able to do a `git pull` at any time to pull new changes down. All of the configs are ignored, so they shouldn't cause any merge issues.

**Comment by destiny117** [comment]
Closing this, if you need additional help open a new issue
