### ISSUE TITLE
Latest Dev build error on launch.

### ISSUE THREAD

**Issue by charredchar** [j-e-k/poketrainer#277]
So this looks like a config error but to make sure I trashed everything and started from scratch and it still pops up.

> C:\Users\Char\Desktop\poketrainer-develop>pokecli.py -i 0
> Traceback (most recent call last):
>   File "C:\Users\Char\Desktop\poketrainer-develop\pokecli.py", line 178, in <module>
>     main()
>   File "C:\Users\Char\Desktop\poketrainer-develop\pokecli.py", line 117, in main
>     config = init_config()
>   File "C:\Users\Char\Desktop\poketrainer-develop\pokecli.py", line 85, in init_config
>     load.update(json.load(data))
>   File "C:\Python27\lib\json\__init__.py", line 291, in load
>     **kw)
>   File "C:\Python27\lib\json\__init__.py", line 339, in loads
>     return _default_decoder.decode(s)
>   File "C:\Python27\lib\json\decoder.py", line 364, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
>     obj, end = self.scan_once(s, idx)
> ValueError: Expecting property name: line 94 column 3 (char 2776)
> 
> C:\Users\Char\Desktop\poketrainer-develop>

Config for reference.

> {
>   "accounts": [
>     {
>       "auth_service": "google",
>       "username": "cut",
>       "password": "cut",
>       "location": "lat/long",
>       "GMAPS_API_KEY": "cut",
>       "BEHAVIOR": {
>         "USE_GOOGLE": true,
>         "STEP_SIZE": 4,
>         "WANDER_STEPS": 20,
>         "EXPERIMENTAL": true,
>         "SKIP_VISITED_FORT_DURATION": 600,
>         "SPIN_ALL_FORTS": true,
>         "STAY_WITHIN_PROXIMITY": 9999,
>         "AUTO_USE_LUCKY_EGG": false
>       },
>       "CAPTURE": {
>         "CATCH_POKEMON": true,
>         "MIN_FAILED_ATTEMPTS_BEFORE_USING_BERRY": 2,
>         "MAX_CATCH_ATTEMPTS": 10
>       },
>       "EGG_INCUBATION": {
>         "ENABLE": true,
>         "USE_DISPOSABLE_INCUBATORS": true,
>         "BIG_EGGS_FIRST": true
>       },
>       "POKEMON_EVOLUTION": {
>         "PIDGEY": 12,
>         "WEEDLE": 12
>       },
>       "POKEMON_CLEANUP": {
>         "MIN_SIMILAR_POKEMON": 1,
>         "MAX_SIMILAR_POKEMON": 999,
>         "KEEP_POKEMON_NAMES": ["MEWTWO"],
>         "RELEASE_METHOD": "CLASSIC",
>         "RELEASE_METHOD_CLASSIC": {
>           "KEEP_CP_OVER": 1000,
>           "KEEP_IV_OVER": 80,
>           "KEEP_IV_ONLY_WITH_PERCENT_CP": 20,
>           "MAX_POKEMON_HIGH_IV": 999
>         },
>         "RELEASE_METHOD_DUPLICATES": {
>           "RELEASE_DUPLICATES_MAX_SCORE": 1000,
>           "RELEASE_DUPLICATES_SCALAR": 0.9
>         },
>         "SCORE_METHOD": "IV",
>         "SCORE_METHOD_FANCY": {
>           "WEIGHT_IV": 0.5,
>           "WEIGHT_LVL": 0.5
>         }
>       },
>       "MIN_ITEMS": {
>         "ITEM_POTION": 0,
>         "ITEM_SUPER_POTION": 0,
>         "ITEM_HYPER_POTION": 0,
>         "ITEM_MAX_POTION": 999,
>         "ITEM_POKE_BALL": 0,
>         "ITEM_GREAT_BALL": 0,
>         "ITEM_ULTRA_BALL": 999,
>         "ITEM_RAZZ_BERRY": 50,
>         "ITEM_REVIVE": 10,
>         "ITEM_MAX_REVIVE": 999
>       },
>       "NEEDY_ITEM_FARMING": {
>         "ENABLE": false,
>         "POKEBALL_CONTINUE_THRESHOLD": 50,
>         "POKEBALL_FARM_THRESHOLD": 10,
>         "FARM_IGNORE_POKEBALL_COUNT": false,
>         "FARM_IGNORE_GREATBALL_COUNT": false,
>         "FARM_IGNORE_ULTRABALL_COUNT": false,
>         "FARM_IGNORE_MASTERBALL_COUNT": true,
>         "FARM_OVERRIDE_STEP_SIZE": -1
>       },
>       "CONSOLE_OUTPUT": {
>         "LIST_POKEMON_BEFORE_CLEANUP": true,
>         "LIST_INVENTORY_BEFORE_CLEANUP": true
>       }
>     },
>     {
>       "auth_service": "ptc",
>       "username": "someusername",
>       "password": "password",
>       "location": "University of Southern California, Los Angeles, CA",
>       "BEHAVIOR": {
>         "USE_GOOGLE": false
>       }
>     }
>   ],
>   "defaults": {
>       "_info": "copy values to this section to use them for all accounts",
>       "_info2": "account settings will always override defaults",
>   }
> }
>

**Comment by mdjong1** [comment]
Take out ```"_info": "copy values to this section to use them for all accounts",
"_info2": "account settings will always override defaults",```

**Comment by charredchar** [comment]
I was wondering if that was causing it or not. This brings up another question that I had issue with. There are some settings I've removed, as you can see, that I first attempted to just comment out but it would cause a config error. Is commenting out not supported in the config or did I somehow do that wrong?

**Comment by mdjong1** [comment]
Unfortunately JSON is a pure data structure, and doesn't support commenting out stuff

**Comment by infinitewarp** [comment]
Those presence lines are actually OK in general. The real problem is the trailing comma on the last line: JSON doesn't support trailing commas.

**Comment by j-e-k** [comment]
Closing
