### ISSUE TITLE
Deploy to Heroku-Button

### ISSUE THREAD

**Issue by filpet** [j-e-k/poketrainer#299]
Should we integrate a "Deploy to Heroku"-Button? Quite useful for non-developers.

https://devcenter.heroku.com/articles/heroku-button

**Comment by j-e-k** [comment]
I think a docker tutorial rather than heroku might be more helpful?

Thoughts all?

**Comment by sftwninja** [comment]
@j-e-k Agreed. I don't feel like this project would be suitable for Heroku without at least a Hobby plan. You need two workers, `web` and `bot`, and they need to run around the clock, something the free plan restricts.

However, I feel it's a great candidate for something like a DigitalOcean or EC2 tutorial through Docker.

**Comment by beeedy** [comment]
Agreed heroku is not the best option, but a tutorial on the lines of "click this" and "type this" may be beneficial. One thing to consider is that if we start to enable people that do not have the technical background to troubleshoot, we may see a large increase in questions. Just something to consider before making the setup idiot proof!

**Comment by destiny117** [comment]
Since there is now a tutorial on Docker in the readme :+1: i'm closing this
