### ISSUE TITLE
New Release Method

### ISSUE THREAD

**Issue by destiny117** [j-e-k/poketrainer#303]
In an effort to get rid of all the confusion around the releasing method, i'm trying to define a new release method that offers all the features needed as simple as possible.

CLASSIC method will behave as before again, but we now have the method CUSTOM with more precise configuration options while not touching the functionality of the DUPLICATES method. Each method is independent of the others.

The main goal is to provide seperate filtering options for IV and CP and giving as much control as possible

But i will not create another pull-request again without everyone being ok with it.

This is what i've come up so far:
```
      "RELEASE_METHOD": "CLASSIC",
      "RELEASE_METHOD_CLASSIC": {
        "KEEP_CP_OVER": 500,
        "KEEP_IV_OVER": 50
      },
      "RELEASE_METHOD_CUSTOM": {
        "ALWAYS_KEEP_CP_OVER": 1000,
        "ALWAYS_KEEP_IV_OVER": 90,
        "ALWAYS_RELEASE_BELOW_LEVEL": 0,
        "BEST_CP": {
          "MIN_AMOUNT": 2,
          "KEEP_ADDITIONAL_SCALAR": 0.9,
          "MAX_AMOUNT": 999
        },
        "BEST_IV": {
          "MIN_AMOUNT": 2,
          "KEEP_ADDITIONAL_SCALAR": 0.8,
          "MAX_AMOUNT": 999,
          "IGNORE_BELOW": 50
        }
      },
      "RELEASE_METHOD_DUPLICATES": {
        "RELEASE_DUPLICATES_MAX_SCORE": 1000,
        "RELEASE_DUPLICATES_SCALAR": 0.9
      },
```

Some more info about the CUSTOM method:
- ALWAYS_KEEP_CP_OVER and ALWAYS_KEEP_IV_OVER will behave like in the classic method, though you can set them higher (especially IV) since you have more control within BEST_CP and BEST_IV.
- ALWAYS_RELEASE_BELOW_LEVEL shall check the actual pokemon level and applies to all pokemon, no matter their IV / CP. It's mostly for those that don't want to keep high-iv pokemons with a very low level.
- Filters within BEST_CP and BEST_IV shall be combined with OR, meaning in the example you will keep at least 2 high-cp and 2 high-iv pokemons (as long as the 2 high-cp are not the same as the 2 high-ivs, then it's just 2)

I tried to keep the options self-explanatory, however i undestand it's a lot of configuration options, is it still too complicated? Do you have a simpler solution? Is there something essential missing?

Awaiting your feedback @j-e-k @beeedy @xezero @dannydotco

**Comment by xezero** [comment]
I like the way it's headed! Level though might be confusing for people since not many people know how it's calculated or that it even exists, but an explanation for it  and how it relates to trainer level would solve that :)

Also, we should order the parameters by their priority (for less confusion) so ALWAYS_RELEASE_BELOW_LEVEL should probably move to the top, and maybe rename the other two like OTHERWISE_KEEP_CP_OVER and OR_KEEP_IV_OVER. That way it's absolutely clear what is always checked and what is checked after and OR'd together (rather than AND'd)

I'll try to think about some improvements upon this, if any, while on the road, otherwise looks pretty good so far!

**Comment by beeedy** [comment]
I like where this is going and really think this is what we need (or at least something that really isolates these methods). I've been afk most weekend, so sorry if this is old news, but for the releasing duplicates method, how do we now determine how score is calculated? 

I agree with @xezero in regards to how to organize and phrase the various parameters, almost so it reads like a fill-in-the-blank type story!

**Comment by FendleTruck** [comment]
Once the web view allows a simple means to transfer we may not need to automate this. Frankly, beyond IV and CP some players may favor high stamina, certain move-sets, etc. Checkboxes to set up pokemon for bulk-transfer would solve all of this. I think the next master release may have something like this, but it's hard for me to tell...

**Comment by xezero** [comment]
Well we would still want at least a basic filtering of some sort since a lot of people just leave the bot on and don't check the web view often.

**Comment by destiny117** [comment]
This is now merged with @356

Options are ordered by their priority now. I also experimented with naming them OTHERWISE... OR... but i couldn't come up with a clean naming that would not be confusing in some way, so i kept the normal naming more or less.

check the new example conf and readme and open new issues or write me in slack if you still have questions or concerns
