### ISSUE TITLE
Multiple account configs

### ISSUE THREAD

**Issue by russellg89** [j-e-k/poketrainer#305]
Trying to run a second account and it does not look like the configs for account 0 translate to account 1. When I try to add those configs it does not want to run the json. How do you set configs for the 2nd account?

**Comment by rirze** [comment]
Use the `defaults` key, look in `config.json.example` in the repository for an example. Any keywords in `defaults` will be applied to all accounts.

**Comment by destiny117** [comment]
if it does not want to run your config.json there is probably a issue like missing or too many ,
you should see a line number on startup

and yes what rirze suggested might be useful to keep account sections minimal to you
