### ISSUE TITLE
[Discussion] Which branch to target for commits and pull requests?

### ISSUE THREAD

**Issue by infinitewarp** [j-e-k/poketrainer#310]
It looks like some commits and pull requests land directly on the `master` branch instead of the `develop` branch, and right now the `develop` branch is actually *behind* `master` by 11 commits. Is this intentional? Should I try to rebase/merge `develop` over the recent commits on `master` and create a new PR to get `develop` back on top? Or is this a deliberate choice?

Just trying to understand the rationale. I'm used to `master` being the "golden" release branch that only gets merges from the development/feature branches, in our case `develop`.

Also, what are your thoughts on when to merge `develop` into `master`? I figure it's pretty  ad hoc at the moment, but I was wondering if you intend to do it every few days, after manually testing things, or anything else.

TIA!

**Comment by j-e-k** [comment]
The master branch I cherry picked in some commits that were fixing broken things. In general though you are right in that we should have master be golden and dev being dev. I welcome your thoughts as to overall project structure and development practices. Has been really helpful to have someone (you) bringing sanity to this project. Long story short, very little of the code smell is deliberate...
