### ISSUE TITLE
Set up Travis CI account

### ISSUE THREAD

**Issue by infinitewarp** [j-e-k/poketrainer#311]
@j-e-k : If you set up your account on travis-ci.org (and update the README link), that should give you automatic checks on all new pull requests. Very handy for catching bugs before merging someone else's code even though the merge itself is "clean".

e.g. https://github.com/infinitewarp/poketrainer/pull/1

![example screenshot](http://imgur.com/ic1Xv3i.png)

**Comment by j-e-k** [comment]
Will get this done soon 😄

**Comment by infinitewarp** [comment]
@j-e-k *bump*

It shouldn't take you more than five minutes. They just use OAuth with your Github account and boom you're in! It's super easy. 😀 

I really think we need this ASAP to keep regressions at bay. I just saw and fixed another recent merge that introduced *actual* syntax errors, not just style problems, to the develop branch. Travis will help prevent those problems by showing us the test results inline with the PR (like the screenshot above) so you can know *not* to merge until things are clean.

**Comment by j-e-k** [comment]
ok doing now!

**Comment by j-e-k** [comment]
Done I really should have done this yesterday 😓 😓 😢

**Comment by j-e-k** [comment]
And I made travis unhappy again with my latest merge, I should really be less merge crazy
