### ISSUE TITLE
Stuck on same fort

### ISSUE THREAD

**Issue by esfomeado** [j-e-k/poketrainer#314]
Hi,

The bot sometimes gets stuck on the same fort and tries to walk to it over and over when has another forts close to them.

**Comment by rirze** [comment]
Could you try another location or perhaps share that location so we can figure out the specifics of this issue?

**Comment by esfomeado** [comment]
Happens due the recent changes it seems.
MAP_OBJECTS not returning any fort.

**Comment by destiny117** [comment]
This should have been fixed when we fixed the new api rate limits. Please open a new issue if you have the same problem again
