### ISSUE TITLE
New errors walking to fort

### ISSUE THREAD

**Issue by cryzies** [j-e-k/poketrainer#318]
http://i.imgur.com/fTDMf7Oh.jpg

Started today

**Comment by j-e-k** [comment]
Is it still broken on latest develop?

**Comment by fil676** [comment]
Develop fixed that issue for me @j-e-k , it seems to be a problem with the current master

**Comment by cryzies** [comment]
@fil676 @j-e-k where can I find the latest develop? This is from the current master.

**Comment by infinitewarp** [comment]
@cryzies https://github.com/j-e-k/poketrainer/tree/develop

**Comment by cryzies** [comment]
Thanks, I'm just gonna copy paste the segment of code that was breaking

**Comment by cryzies** [comment]
Checked the code and compared it to where the error was occuring, seems the code is the exact same for walk to fort and spin all forts. I disabled spin all forts and it works fine now. Maybe it has something to do with https://www.reddit.com/r/pokemongodev/comments/4vev3u/psa_get_map_objects_min_refresh_seconds_5/

**Comment by cryzies** [comment]
https://github.com/j-e-k/poketrainer/pull/340
