### ISSUE TITLE
web.py fails on python3

### ISSUE THREAD

**Issue by infinitewarp** [j-e-k/poketrainer#322]
```
builtins.TypeError
TypeError: the JSON object must be str, not 'bytes'
```
and a long stack trace ending on:
```
File "/Users/infinitewarp/Documents/code/poketrainer/web.py", line 50, in get_api_rpc
data = json.loads(data.encode() if len(data) > 0 else '{}')
File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
I forgot to verify the web client on python3 when I was verifying the cli bot. 😭 I'll take another look at it now and prepare a pull request shortly…

**Comment by infinitewarp** [comment]
Oh, and since it probably wasn't clear from that comment, `web.py` *does* still work fine on python2.

**Comment by j-e-k** [comment]
Just need to decode ;) 

Lmk when you have a pr working

**Comment by rirze** [comment]
This looks like it's related to how Python 3 handles strings compared to Python 2...

**Comment by infinitewarp** [comment]
Yeah, easy fix. Already have it handled locally, but distracted with another py2/py3 issue atm. Will post what I have so far in a moment…

**Comment by infinitewarp** [comment]
@j-e-k: it should be good to go now!
