### ISSUE TITLE
ImportError: No module named gevent

### ISSUE THREAD

**Issue by ununhexiumz** [j-e-k/poketrainer#327]
Hey, having issues with the develop branch - 
keep getting the error `ImportError: No module named gevent`

Installed reqs, tried installing gevent on its own (which was successful) still having same error. Any ideas?

Thanks for the great work guys. And the help.

**Comment by infinitewarp** [comment]
How exactly did you install the requirements and how exactly are you running `pokecli.py`? Are you using a virtual environment, or have you installed requirements into your root system library? What does the stack trace contain when you get that error?

You might want to try `pip install -U -r requirements.txt` to force pip to upgrade/overwrite if there are incorrect versions already installed.

**Comment by rirze** [comment]
@ununhexiumz If doing what @infinitewarp suggested still doesn't solve it, can you try opening a python prompt (type `python` at the command prompt/terminal) and see what happens when you `import gevent` from there?

**Comment by ununhexiumz** [comment]
Virtualenv worked like a beauty. Thanks @infinitewarp 

and thanks for the extra suggestion @rirze
