### ISSUE TITLE
What should I put into the "default"

### ISSUE THREAD

**Issue by IllidanU** [j-e-k/poketrainer#331]
`"defaults": {
      "_info": "copy values to this section to use them for all accounts",
      "_info2": "account settings will always override defaults"
  }`
I don't get it. What should be insert here? Any example?

Sorry for bothering but I really tried something and always got ERROR

**Comment by joshpalan** [comment]
You put any values you want present in all accounts created. For example, if you have a google API key you can enter ```GMAPS_API_KEY: "your api key"``` so that you don't have to enter your key in every account you create.

**Comment by IllidanU** [comment]
@joshpalan Thanks for your help!
