### ISSUE TITLE
How to open pull requests?

### ISSUE THREAD

**Issue by joshpalan** [j-e-k/poketrainer#333]
I changed up the logic so that the values in take_next_ball are pulled in from the config.json, but I don't know the process you guys have in place for opening pull requests and creating branches. I don't want to dirty up the repo or step on any toes so if it's alright to just create branches and open pull requests let me know!

**Comment by sftwninja** [comment]
Fork the repository, work on the code in your own branch and ensure that branch originated from `develop`, not master, and submit a PR against the `develop` branch.

Thanks!

**Comment by joshpalan** [comment]
No, thank you for the great tool!
