### ISSUE TITLE
trouble starting the bot

### ISSUE THREAD

**Issue by 750z** [j-e-k/poketrainer#336]
Thought id join the slack channel but they are literally no help whatsoever.

Im having trouble just trying to start the bot, recently found out that this was the original bot where tomthebotter forked and made his own from this. So i thought id give this a try but I cant seem the bot to even load. Anyidea what im doing wrong?

In the cmd im writing C:\Python27\python pokecli.py which just gives me an error

**Comment by HibikiFox** [comment]
so the command needs to be run from wherever you unzipped the files

IE

c:\uses\Your_User_Name\downloads\Poketrainer_develop\

you need to be in that folder at the command prompt to run the python script

**Comment by rirze** [comment]
Telling us the error would help in figuring out what went wrong.

**Comment by 750z** [comment]
http://puu.sh/qkIkg/0f53e3aa8b.png

thats the error i get.

And yes the file itself isnt in the python27 folder.

**Comment by teh3vil** [comment]
@rirze you need to type
`python pokecli.py -i 0`

-i tells it to use the config.json file to read in information, the 0 tells it which account settings to use. As long as everything else has been done (pip install -r requirements.txt, setup.py) then it should at least boot :)

**Comment by 750z** [comment]
@HibikiFox @teh3vil  cheers for your guys help. I finally have it running. Needed to run -requirements.txt haha. 

Just another question while you guys are here, but in config, we have a option to throw pokemon. Just separating the pokemon by commas would be good right?

Eg:  "THROW_POKEMON_NAMES": ["PIDGEY, ZUBAT, TENTACOOL"],

**Comment by teh3vil** [comment]
Glad you got it working @750z :)
