### ISSUE TITLE
Why RELEASE_METHOD_CLASSIC does not use SCORE_METHOD for pokemon sorting

### ISSUE THREAD

**Issue by chronocrux** [j-e-k/poketrainer#374]
Before new update, there was config DEFINE_POKEMON_LV, which use as sorting method before transfering pokemon. As per today's update, it changes with SCORE_METHOD, but i found this config is not use for RELEASE_METHOD_CLASSIC and it is not mentioned in the description that our pokemon will be sorted by CP.

Could I know why it is dropped from CLASSIC sorting?

**Comment by destiny117** [comment]
it was changed because that's how the classic method originally worked and some ppl were confused about the new stuff including the score, do you have a use case where you need it?

**Comment by chronocrux** [comment]
I just want to sort my pokemon by IV and check by KEEP_IV_OVER before releasing the pokemon. I set KEEP_CP_OVER quite high enough to release high CP, but low IV. 

I found other methods a bit confusing. Or could you help me to elaborate it detail so others can use another method to fulfill this case?

**Comment by destiny117** [comment]
what you want is mostly possible with the advanced method, though i agree it would be easier for you by just sorting by score... maybe will add that again with the next merge

in the meantime here's how you could seet it up:
```
      "MIN_SIMILAR_POKEMON": 1,
      "RELEASE_METHOD": "ADVANCED",
      "RELEASE_METHOD_ADVANCED": {
        "ALWAYS_RELEASE_BELOW_LEVEL": 0,
        "KEEP_CP_OVER": 1000,
        "KEEP_IV_OVER": 90,
        "BEST_CP": {
          "MIN_AMOUNT": 0
        },
        "BEST_IV": {
          "MIN_AMOUNT": 2
        }
      },
```

`BEST_IV`->`MIN_AMOUNT` would replace your current `MIN_SIMILAR_POKEMON`, though it will still keep MIN_SIMILAR_POKEMON based on CP. You could set `"MIN_SIMILAR_POKEMON" = 0` but then it will not keep any pokemons inside `THROW_POKEMON_NAMES`

**Comment by stolencatkarma** [comment]
looked solved to me. closing
