### ISSUE TITLE
Classic Method not working as it should, general issues with config file

### ISSUE THREAD

**Issue by rirze** [j-e-k/poketrainer#378]
Somewhere along the way, the classic method was not retrieving "KEEP_CV_OVER" and "KEEP_IV_OVER" from the config file, thus setting these values to the default 0. This kept filling up my pokemon inventory for me and never released any. The following is the relevant part of my config:

```
"POKEMON_CLEANUP": {
            "MIN_SIMILAR_POKEMON": 1,
            "MAX_SIMILAR_POKEMON": 999,
            "KEEP_POKEMON_NAMES": [],
            "THROW_POKEMON_NAMES": ["PIDGEY"],
            "RELEASE_METHOD": "CLASSIC",
            "RELEASE_METHOD_CLASSIC": {
                "KEEP_CP_OVER": 1200,
                "KEEP_IV_OVER": 97,
                "KEEP_IV_ONLY_WITH_PERCENT_CP": 0,
                "MAX_POKEMON_HIGH_IV": 999
            },
            "RELEASE_METHOD_DUPLICATES": {
                "RELEASE_DUPLICATES_MAX_SCORE": 1000,
                "RELEASE_DUPLICATES_SCALAR": 0.9
            },
            "SCORE_METHOD": "IV",
            "SCORE_METHOD_FANCY": {
                "WEIGHT_IV": 0.5,
                "WEIGHT_LVL": 0.5
            }
        },
```

I can get the classic method to work again by changing `processConfig` in `pgoapi/release/classic.py` to:
```
def processConfig(self, config):
        self.config = config
        
        self.keep_pokemon_ids = map(lambda x: getattr(Enums_pb2, x), config.get("KEEP_POKEMON_NAMES", []))
        self.throw_pokemon_ids = map(lambda x: getattr(Enums_pb2, x), config.get("THROW_POKEMON_NAMES", []))
        self.KEEP_CP_OVER = self.config.get("RELEASE_METHOD_CLASSIC",{}).get('KEEP_CP_OVER', 0)
        self.KEEP_IV_OVER = self.config.get("RELEASE_METHOD_CLASSIC",{}).get('KEEP_IV_OVER', 0)
        self.MAX_SIMILAR_POKEMON = self.config.get('MAX_SIMILAR_POKEMON', 999)
        self.MIN_SIMILAR_POKEMON = self.config.get('MIN_SIMILAR_POKEMON', 1)
    
```

Before, the variables were being set without getting `"RELEASE_METHOD_CLASSIC"` first, thus setting it to the alternative value. I'm not sure if the advanced methods suffer from this as well. 

Also I'm curious if we can get some better documentation on the config file, since people are filing issues on it, and it seems to cause errors like these. I'm not able to push a pull request at the moment since I'm not at my development environment, so feel free to make a hotfix if you can.

**Comment by HibikiFox** [comment]
I tried working on a wiki page.... but SMH it changes so frequently it is hard to keep up with Kudos to @j-e-k  for all the work on the readme file at least

**Comment by dwayn** [comment]
It seems I made some of the config handling code overly complex last night. I am working on cleaning that up now (and fixing this bug in the process), so give me a bit and I should have a PR ready

**Comment by j-e-k** [comment]
@dwayn @destiny117 Once you guys have it working can you go ahead and merge it to master?

**Comment by HibikiFox** [comment]
Master or Dev?

**Comment by destiny117** [comment]
master is not effected by this, develop is fixed now thanks to @dwayn, closing
