### ISSUE TITLE
How to make the bot randomly pause for random hours? 

### ISSUE THREAD

**Issue by russellg89** [j-e-k/poketrainer#386]
How to make the bot randomly pause for random hours?  Making it take human-like breaks. Such as 8.xx hours here and 2.xx hours there.

**Comment by loveinpin** [comment]
make Google as ur best friend 

go terminal set this 

`shutdown.exe -s -t 60  ` unit is second 

or 

`at 00:00 Shutdown -s ` it would shutdown PC automatically at set time 

only  shut program down 
--- ProcessKO

**Comment by rirze** [comment]
@russellg89 I agree with @loveinpin's suggestion, it's hard to implement a feature like this without implementing os-specific routines. You probably better off try to wrap `python pokecli.py -i#` in some kind of wrapper script for your operating system. For example if you're using linux, look at this [example](http://stackoverflow.com/questions/5161193/bash-script-that-kills-a-child-process-after-a-given-timeout). I'm not sure what the equivalent would be for windows, but maybe someone else here can offer a solution.

**Comment by j-e-k** [comment]
Going to agree with them, with as many features as the bot currently has, I do not think we really need this one....
