### ISSUE TITLE
requirements.txt install error, 0rpc

### ISSUE THREAD

**Issue by spudink** [j-e-k/poketrainer#387]
Getting this error with "pip install -r requirements.txt" on the latest:

Error [Error 2] The system cannot find the file specified while executing command git clone -q git://github.com/0rpc/zerorpc-python.git C:\pokebot\src\zerorpc
Cannot find command 'git'

**Comment by rirze** [comment]
https://www.git-scm.com/downloads
You need git on your system. In short git is a problem that pull code from github and similar repositories onto your computer. One of the requirements for this project requires a building a library from github, hence the need for git.

**Comment by j-e-k** [comment]
Closing, open a new issue if you need help
