### ISSUE TITLE
Add an "Evolve" button next to the "Transfer" button in the Pokemon list

### ISSUE THREAD

**Issue by miniyuuzhan** [j-e-k/poketrainer#389]
Would it be possible to add an "evolve" button for each pokemon that has enough candies to be evolved ?

This probably means to declare an "evolution chart" somewhere in the code.

**Comment by HibikiFox** [comment]
Already requested, but for the pokemon info page
#382

**Comment by miniyuuzhan** [comment]
Ah yes, exact. It would be useful in the pokemon list because I already have all the info I need on this page to choose if I want to evolve a pkmn or not.

I'm open.

**Comment by MRokas** [comment]
#404 

`git fetch origin pull/404/head:Evole && git stash && git checkout Evolve`
