### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Timmyplumu** [j-e-k/poketrainer#395]
I followed the guide completely installing all required programs, and configuring the config.json.

This is the error I am getting.

> Timothys-MacBook-Pro:pokemonbot Timmy$ python pokecli.py
> Traceback (most recent call last):
>   File "pokecli.py", line 175, in <module>
>     main()
>   File "pokecli.py", line 113, in main
>     config = init_config()
>   File "pokecli.py", line 81, in init_config
>     load.update(json.load(data))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
>     **kw)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
> 

Please help me fix this!

**Comment by HibikiFox** [comment]
your json file is malformed (something is not right)

https://jsonformatter.curiousconcept.com/

Copy and paste it in that site and it will tell you what is wrong

**Comment by stolencatkarma** [comment]
problem with your setup not the code. closing.
