### ISSUE TITLE
Get This Error With Latest Repo?

### ISSUE THREAD

**Issue by freakyfreak87** [j-e-k/poketrainer#400]
I downloaded the latest repo today, I havent done anything in a day or two but now when trying to run the bot I keep getting this:

`
C:\Users\XXXXX\Downloads\poketrainer-master1\poketrainer-master>python pokecli.py -i 0
Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    import gevent
ImportError: No module named gevent

C:\Users\XXXX\Downloads\poketrainer-master1\poketrainer-master>`

**Comment by jmhummel** [comment]
did you try updating your dependencies using `pip install -r requirements.txt`?

**Comment by freakyfreak87** [comment]
Yes, and I'm doing so it errors with something about git not found, idk what happened lol

**Comment by zatipnis** [comment]
When referencing errors, please post exact quotations.

Try `cd poketrainer&&sudo python setup.py`

**Comment by freakyfreak87** [comment]
I will do as soon as I get home, I am currently away from home

**Comment by rirze** [comment]
see #387 : if the only problem is `git not found` error

**Comment by infinitewarp** [comment]
Yeah, what @rirze said. Unfortunately, we need a bleeding-edge version of one of the dependencies, and that means you have to have git installed to download/install it. Try installing git and see if this issue goes away.

**Comment by freakyfreak87** [comment]
okay, and now after installing git I keep on getting similar things to this, and this is after d/l a fresh repo in zip form:
``
C:\Users\Jeremy\Desktop\poketrainer-master1\poketrainer-master>python pokecli.py -i 0
Traceback (most recent call last):
  File "pokecli.py", line 41, in <module>
    import zerorpc
ImportError: No module named zerorpc

C:\Users\Jeremy\Desktop\poketrainer-master1\poketrainer-master>

**Comment by rirze** [comment]
@freakyfreak87 Assuming that pip was able to install the dependencies without error, this might signal a problem with your overall development environment (specifically your python path). I would recommend using virtual environments for python, but I've never used them on Windows before. Perhaps someone with experience with virtualenv on Windows can offer their advice.

**Comment by freakyfreak87** [comment]
Idk whats going on i've previously been using the bot just fine until the latest repo, I have had python/git installed "now" but after the latest repo is when all these errors started popping up for me, never before previously, I was able to bot just fine and it was working great, then this started not long after the latest repo on Windows 10

**Comment by joshpalan** [comment]
Try this:
`sudo pip install -r requirements.txt --upgrade`

**Comment by rirze** [comment]
@joshpalan Pretty sure he's using windows, so the `sudo` wouldn't have be relevant here. I would recommend seeing where pip installed these libraries during the installation process. Then somehow tell Windows the correct python path.

**Comment by freakyfreak87** [comment]
Why would it work well for over a week then start this? Previously all pip commands worked fine, can I just rerun a pip install?

**Comment by joshpalan** [comment]
I would suggest trying to rerun pip install with the --upgrade flag.

**Comment by q32103940** [comment]
this is because the reference to zerorpc in requirements.txt is using git:// protocol. this should have been declared as a requirement too . cachetools was also introduced at the same time. i manually installed these two .py's

**Comment by cod3b0t** [comment]
virtualenv for windows : https://pypi.python.org/pypi/virtualenvwrapper-win self explanatory

**Comment by Myhorta** [comment]
What is your python version?
Maybe do `python --version?`

**Comment by stolencatkarma** [comment]
please come to - https://pkre.slack.com/messages/poketrainer/ - for general help. this is not a issue with the code but with your setup.
