### ISSUE TITLE
"Nidoran Male" and "Nidoran Female" name error

### ISSUE THREAD

**Issue by q32103940** [j-e-k/poketrainer#407]
config.json
> "THROW_POKEMON_NAMES": ["CUBONE", "DODUO", "NIDORAN MALE", "NIDORAN FEMALE"],

crashes unless both nidorans are removed. any idea why? pokemon.en.json spells it like that, and the rest of the pokemon are ok.

**Comment by destiny117** [comment]
You have to name then according to the [AeonLucidProtos_Pokemon](https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Enums/PokemonId.proto), this is also in the readme, though a bit out of place now

**Comment by stolencatkarma** [comment]
NIDORAN_FEMALE 
NIDORAN_MALE 

are the proper way to do it. closing this.
