### ISSUE TITLE
No module named gevent

### ISSUE THREAD

**Issue by cybercreep** [j-e-k/poketrainer#416]
Hello,
Can anyone solve this problem?
I got this message.

![image](https://cloud.githubusercontent.com/assets/20833862/17394194/0404fe8c-5a52-11e6-8a0e-fc91a774b046.png)

Thanks

**Comment by destiny117** [comment]
you would have to install the requirements, though keep in mind currently no bot is working due to API changes so it's pointless atm, see #414
