### ISSUE TITLE
Trip distance 0.00 meters, and can't access Web UI

### ISSUE THREAD

**Issue by sadatnfs** [j-e-k/poketrainer#417]
1) Using most of the default options, I never seem to be able to actually do any travelling. The trip distance always shows to be 0.00 meters, and all the trips return with no fruition.

2) I can't seem to be able to access the web UI for tracking my Pokemon and trips. I run "sudo python web.py "username" " and it gives "Running on http://0.0.0.0:5000/" , but I can't seem to access that page at all. Thoughts?

**Comment by sadatnfs** [comment]
Never mind, got it up and running! THanks!!!

**Comment by j-e-k** [comment]
Niantic broke all APIs. The bot will be fixed once the changes have been reverse engineered. #414
