### ISSUE TITLE
WindowsError 126

### ISSUE THREAD

**Issue by Simennzz** [j-e-k/poketrainer#435]
Hey I get this error after installing requirements.txt and running python, didnt get this with last version

![image](https://cloud.githubusercontent.com/assets/4706694/17462883/a63d0d06-5cba-11e6-8de9-4513205cc7df.png)

**Comment by NathanWaudby** [comment]
How was this fixed please?

**Comment by j-e-k** [comment]
You need to find encrypt.dll and place it into the folder you have pokecly.py. Then you run with `-e encrypt.dll` at the end

**Comment by NathanWaudby** [comment]
I have downloaded the one included in your pastebin but still the same error, do you know how to generate a fresh one on windows?
