### ISSUE TITLE
OSError: libencrypt.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sadatnfs** [j-e-k/poketrainer#461]
Any thoughts on this error?

**Comment by j-e-k** [comment]
Do you have the encrypt lib built and in the same directory as pokecli.py?

**Comment by sadatnfs** [comment]
I don't (have either)! (a noob here).

I downloaded the encrypt package from pip, but it seems like I'll need to do something else eh?

**Comment by stolencatkarma** [comment]
join us here - https://pkre.slack.com/ room #poketrainer

**Comment by infinitewarp** [comment]
See also: [PROBLEM WITH ENCRYPT? CHECK HERE](https://github.com/j-e-k/poketrainer/issues/436)
