### ISSUE TITLE
Colorized output

### ISSUE THREAD

**Issue by BHGaming** [j-e-k/poketrainer#465]
I am not sure if this has been mentioned before (I did not see any open tickets), but would it be possible to add colors to the various functions of the bot?  For example, Inventory, Pokemon Caught, Fort Spun, Player Info, Egg Status, etc.

If not, could we change every output being tagged as INFO to something more specific, like: Egg, Inventory, Pokemon (catch, release, etc), Fort, Cleanup, etc.

It may just be personal preference, but I have a hard time finding specific data on a scrolling screen of white text where everything is tagged INFO.  Even a on/off function for colors in the config file would be good.

Thanks!

**Comment by teh3vil** [comment]
I've not tried colourising the statuses yet but there is a python package that handles exactly that. I'll see what's possible on the weekend If i get around to editing the message text again.

**Comment by infinitewarp** [comment]
see also: https://github.com/j-e-k/poketrainer/pull/478

**Comment by stolencatkarma** [comment]
this is in latest develop. thanks!
