### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by magnetik89** [j-e-k/poketrainer#488]
Since the refactor, it takes up to 30 seconds for the bot to execute a snipe request. It used to interrupt the event loop immediately.

**Comment by magnetik89** [comment]
I love the bot and don't expect a quick fix for this, just wanted to document it.

**Comment by j-e-k** [comment]
Can you paste the full log of a snipe request for you?

**Comment by stolencatkarma** [comment]
I've looked into this and made some changes. should work smoother now.
