### ISSUE TITLE
Incubate eggs

### ISSUE THREAD

**Issue by esfomeado** [j-e-k/poketrainer#67]
An auto egg incubator is a must.

**Comment by j-e-k** [comment]
It's planned and on the backlog

**Comment by eddawang** [comment]
I added incubation but for some reason going through inventory_items on returns one of the incubators. It works for just that one incubator though.

**Comment by spamfarm** [comment]
@j-e-k 

Mind sharing your backlog either in repo or as issues? I have some spare cycles and am an experienced modder & dev.

**Comment by j-e-k** [comment]
Just got merged into msater.
@spamfarm 
Right now the backlog is really to refactor code so that we can have a web api interact with the bot. The sleeps that we use make this a pain sadly...
