### ISSUE TITLE
Release lower CP pokemon

### ISSUE THREAD

**Issue by aandromeda** [j-e-k/poketrainer#87]
It would be awesome if when deciding to release a duplicated pokemon when       "MIN_SIMILAR_POKEMON": 1 it released the lower CP one.

**Comment by beeedy** [comment]
Pr for essentially this https://github.com/j-e-k/pgoapi/pull/85

**Comment by infinitewarp** [comment]
Closing this since a lot of work has been done recently around determining when to keep/transfer pokemon. Follow @beeedy's link to go down the rabbit hole…
